"""Catalog, downloaders and parsers for results-with-closing-lines datasets.

Companion to the cross-game correlated-parlay experiment. Every source here
was verified to be downloadable through ``raw.githubusercontent.com`` or a
``github.com/<owner>/<repo>/releases/download/`` URL (the only hosts reachable
from the sandbox) and inspected with pandas. Results and caveats are written
up in ``docs/experiments/parlay-data-hunt.md`` (generated by
``scripts/hunt_parlay_data.py``).

All parsers return the common ``GAME_COLUMNS`` layout so that a sport can be
pushed through :func:`to_nflverse_layout` and re-use the existing
``clean_games`` / ``to_team_games`` / ``build_shared_game_pairs`` pipeline.

Sign conventions (same as the rest of the package): ``spread_close`` is the
market's expected ``home - away`` margin, so positive means the home side is
favoured. Moneylines are American odds. Timestamps are UTC.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd
import requests

from geo_model.parlay.config import ParlayConfig, american_to_decimal

RAW_GH = "https://raw.githubusercontent.com"
ALLOWED_URL_PREFIXES = (RAW_GH + "/", "https://github.com/")

GAME_COLUMNS = [
    "sport",
    "source",
    "season",
    "date",
    "home",
    "away",
    "neutral",
    "home_score",
    "away_score",
    "home_ml_open",
    "away_ml_open",
    "home_ml_close",
    "away_ml_close",
    "spread_open",
    "spread_close",
    "total_open",
    "total_close",
    "home_pitcher_id",
    "away_pitcher_id",
]

# Plausible ranges used to blank out scraper glitches (e.g. a total written
# into the spread column). Values outside are set to NaN, never "fixed".
PLAUSIBLE: dict[str, dict[str, tuple[float, float]]] = {
    "nba": {"spread": (-40.0, 40.0), "total": (150.0, 300.0)},
    "nfl": {"spread": (-40.0, 40.0), "total": (20.0, 80.0)},
    "ncaaf": {"spread": (-80.0, 80.0), "total": (20.0, 120.0)},
    "ncaab": {"spread": (-60.0, 60.0), "total": (80.0, 250.0)},
    "mlb": {"spread": (-3.0, 3.0), "total": (4.0, 20.0)},
    "nhl": {"spread": (-3.0, 3.0), "total": (3.0, 10.0)},
}

# When only one of the two SBR rows carries a number, values at or above this
# are read as totals, below as spreads (only NBA/NCAAB are unambiguous).
SBR_TOTAL_THRESHOLD: dict[str, float] = {"nba": 100.0, "ncaab": 100.0, "ncaaf": 40.0, "nfl": 30.0}


# --------------------------------------------------------------------------- #
# Source catalog
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class SourceFile:
    """One downloadable file of a source.

    Attributes:
        url: Download URL (must be on an allowed GitHub host).
        filename: Path relative to ``<data_dir>/<sport>/``.
    """

    url: str
    filename: str


@dataclass(frozen=True)
class SourceSpec:
    """A verified dataset.

    Attributes:
        key: Short unique identifier.
        sport: One of ``mlb, nba, nhl, nfl, ncaab, ncaaf, soccer, tennis``.
        description: What the files are and where they were scraped from.
        seasons: Human-readable coverage.
        files: Files to download.
        closing_lines: Whether closing (not just opening) lines are present.
        starting_pitchers: Whether starters are named (MLB only).
        license: License / terms as visible in the source repo.
        quality: ``excellent`` / ``usable`` / ``weak``.
        notes: Caveats discovered during inspection.
    """

    key: str
    sport: str
    description: str
    seasons: str
    files: tuple[SourceFile, ...]
    closing_lines: bool
    starting_pitchers: bool
    license: str
    quality: str
    notes: str = ""

    @property
    def repo_url(self) -> str:
        """Repository page derived from the first file URL."""
        parts = self.files[0].url.split("/")
        if self.files[0].url.startswith(RAW_GH):
            return f"https://github.com/{parts[3]}/{parts[4]}"
        return "/".join(parts[:5])


_SBR_SEASONS = tuple(f"{y}-{str(y + 1)[-2:]}" for y in range(2007, 2022))


def _finned(sport: str) -> SourceFile:
    return SourceFile(
        url=f"{RAW_GH}/FinnedAI/sportsbookreview-scraper/main/data/{sport}_archive_10Y.json",
        filename=f"sbr_finned_{sport}_2011_2021.json",
    )


def _dillon(folder: str, prefix: str, out_prefix: str) -> tuple[SourceFile, ...]:
    return tuple(
        SourceFile(
            url=f"{RAW_GH}/DillonKoch/Sports_Betting/master/Data/Odds/{folder}/{prefix}%20{s}.xlsx",
            filename=f"sbr_xlsx/{out_prefix}_odds_{s}.xlsx",
        )
        for s in _SBR_SEASONS
    )


def _retrosheet(years: Iterable[int]) -> tuple[SourceFile, ...]:
    out = []
    for y in years:
        name = f"gl{y}.txt" if y == 2024 else f"GL{y}.TXT"
        out.append(
            SourceFile(
                url=f"{RAW_GH}/chadwickbureau/retrosheet/master/seasons/{y}/{name}",
                filename=f"retrosheet/GL{y}.TXT",
            )
        )
    return tuple(out)


def _tennis() -> tuple[SourceFile, ...]:
    files = []
    for y in range(2001, 2015):
        files.append(SourceFile(f"{RAW_GH}/maxfar/tennis-data/master/{y}.csv", f"tennis_data_atp_{y}.csv"))
    for y in range(2015, 2020):
        files.append(
            SourceFile(f"{RAW_GH}/ushinghal19/tennis-betting/main/data/{y}.csv", f"tennis_data_atp_{y}.csv")
        )
    for y in range(2020, 2027):
        files.append(
            SourceFile(
                f"{RAW_GH}/gmalbert/tennis-predictions/main/data_files/{y}.xlsx", f"tennis_data_atp_{y}.xlsx"
            )
        )
    return tuple(files)


SBR_LICENSE = (
    "Repo code MIT; the odds themselves are sportsbookreview(sonline).com archive scrapes "
    "with no stated data license"
)
RETROSHEET_LICENSE = (
    "Retrosheet notice: 'The information used here was obtained free of charge from and is "
    "copyrighted by Retrosheet. Interested parties may contact Retrosheet at www.retrosheet.org.'"
)

SOURCES: tuple[SourceSpec, ...] = (
    SourceSpec(
        key="mlb_sbr_finned",
        sport="mlb",
        description="sportsbookreview.com archive scrape (FinnedAI/sportsbookreview-scraper), one JSON per sport",
        seasons="2011-2021 (2020 shortened)",
        files=(_finned("mlb"),),
        closing_lines=True,
        starting_pitchers=False,
        license=SBR_LICENSE,
        quality="usable",
        notes=(
            "Open+close moneyline, close run line (+odds, 29% blank), open+close total (+odds); "
            "innings scores. No pitchers: join Retrosheet game logs (see attach_starting_pitchers). "
            "Team names are a mix of nicknames and SBR codes (LOS=Dodgers, CUB, KAN, SDG, SFO, TAM)."
        ),
    ),
    SourceSpec(
        key="mlb_sbr_book",
        sport="mlb",
        description="sportsbookreview.com per-book scrape (ArnavSaraogi/mlb-odds-scraper release asset)",
        seasons="2021-04-01 to 2025-08-16",
        files=(
            SourceFile(
                "https://github.com/ArnavSaraogi/mlb-odds-scraper/releases/download/dataset/mlb_odds_dataset.json",
                "sbr_book_mlb_2021_2025.json",
            ),
        ),
        closing_lines=True,
        starting_pitchers=False,
        license=SBR_LICENSE,
        quality="excellent",
        notes=(
            "Opening and closing ML / run line / total per book (DraftKings, FanDuel, Caesars, bet365, "
            "BetMGM, BetRivers); includes spring training (gameType S) and postseason. No pitchers."
        ),
    ),
    SourceSpec(
        key="mlb_retrosheet_gamelogs",
        sport="mlb",
        description="Retrosheet game logs mirrored by Chadwick Baseball Bureau (starting pitchers, scores)",
        seasons="2010-2025 downloaded (repo has 1871-2025)",
        files=_retrosheet(range(2010, 2026)),
        closing_lines=False,
        starting_pitchers=True,
        license=RETROSHEET_LICENSE,
        quality="excellent",
        notes="161-field CSV without header; fields 102-105 are visiting/home starting pitcher id and name.",
    ),
    SourceSpec(
        key="nba_sbr_finned",
        sport="nba",
        description="sportsbookreview.com archive scrape (FinnedAI), NBA",
        seasons="2011-12 to 2021-22 (season label = start year)",
        files=(_finned("nba"),),
        closing_lines=True,
        starting_pitchers=False,
        license=SBR_LICENSE,
        quality="usable",
        notes=(
            "Close ML, open+close spread, open+close total, 2H lines, quarter scores. A few rows carry "
            "swapped spread/total values (blanked by PLAUSIBLE); modern franchise names used throughout."
        ),
    ),
    SourceSpec(
        key="nba_sbr_xlsx",
        sport="nba",
        description="sportsbookreviewsonline.com season workbooks committed in DillonKoch/Sports_Betting",
        seasons="2007-08 to 2021-22",
        files=_dillon("NBA", "NBA%20odds", "nba"),
        closing_lines=True,
        starting_pitchers=False,
        license="No LICENSE file in repo; data is the SBR online archive",
        quality="excellent",
        notes="Two rows per game (V/H), Open/Close hold spread on favourite row and total on the other; ML per team; 2H line.",
    ),
    SourceSpec(
        key="nhl_sbr_finned",
        sport="nhl",
        description="sportsbookreview.com archive scrape (FinnedAI), NHL",
        seasons="2011-12 to 2021-22 (2012-13 lockout, 2019-20/2020-21 shortened)",
        files=(_finned("nhl"),),
        closing_lines=True,
        starting_pitchers=False,
        license=SBR_LICENSE,
        quality="usable",
        notes="Open+close ML, close puck line (+odds, 25% blank), open+close total (+odds), period scores.",
    ),
    SourceSpec(
        key="nfl_sbr_finned",
        sport="nfl",
        description="sportsbookreview.com archive scrape (FinnedAI), NFL",
        seasons="2011-2021",
        files=(_finned("nfl"),),
        closing_lines=True,
        starting_pitchers=False,
        license=SBR_LICENSE,
        quality="usable",
        notes="Redundant with the nflverse games file already used by the experiment; kept as a cross-check.",
    ),
    SourceSpec(
        key="ncaab_sbr_xlsx",
        sport="ncaab",
        description="sportsbookreviewsonline.com NCAA basketball workbooks (DillonKoch/Sports_Betting)",
        seasons="2007-08 to 2021-22",
        files=_dillon("NCAAB", "ncaa%20basketball", "ncaab"),
        closing_lines=True,
        starting_pitchers=False,
        license="No LICENSE file in repo; data is the SBR online archive",
        quality="excellent",
        notes="~4,200 games per season; ML often 'NL' for lopsided games.",
    ),
    SourceSpec(
        key="ncaaf_sbr_xlsx",
        sport="ncaaf",
        description="sportsbookreviewsonline.com NCAA football workbooks (DillonKoch/Sports_Betting)",
        seasons="2007-08 to 2021-22",
        files=_dillon("NCAAF", "ncaa%20football", "ncaaf"),
        closing_lines=True,
        starting_pitchers=False,
        license="No LICENSE file in repo; data is the SBR online archive",
        quality="usable",
        notes="~900 games per season; the 2021-22 file has shifted columns in places (spreads under ML).",
    ),
    SourceSpec(
        key="ncaaf_cfbfastr_lines",
        sport="ncaaf",
        description="cfbfastR-data betting/csv/cfb_line_odds.csv.gz (ESPN multi-book lines)",
        seasons="2006-2019",
        files=(
            SourceFile(
                f"{RAW_GH}/sportsdataverse/cfbfastR-data/master/betting/csv/cfb_line_odds.csv.gz",
                "cfbfastr_cfb_line_odds_2006_2019.csv.gz",
            ),
        ),
        closing_lines=True,
        starting_pitchers=False,
        license="cfbfastR-data repo (MIT for code); ESPN-sourced lines",
        quality="usable",
        notes=(
            "Long format: one row per game x book x market x side (1.09M rows); 'lines' are the last "
            "captured (closing) values, 'opening_lines' mostly missing before 2012. Team abbreviations "
            "need a mapping to resolve home/away."
        ),
    ),
    SourceSpec(
        key="soccer_xgabora",
        sport="soccer",
        description="football-data.co.uk consolidated by xgabora/Club-Football-Match-Data-2000-2025 (+ClubElo)",
        seasons="2000-01 to 2026-27 (38 divisions)",
        files=(
            SourceFile(
                f"{RAW_GH}/xgabora/Club-Football-Match-Data-2000-2025/main/data/Matches.csv",
                "xgabora_matches_2000_2026.csv",
            ),
        ),
        closing_lines=False,
        starting_pitchers=False,
        license="MIT (repo); underlying football-data.co.uk data is free to use",
        quality="usable",
        notes=(
            "238,858 matches with Bet365 1X2, max odds, O/U 2.5 and Asian handicap. These are the "
            "football-data.co.uk pre-match snapshot (Friday/Tuesday), not closing prices."
        ),
    ),
    SourceSpec(
        key="soccer_football_data_closing_sample",
        sport="soccer",
        description="Raw football-data.co.uk E0 2021-22 file (has *C closing columns) from pawelp0499/football-prediction-model",
        seasons="2021-22 only (EPL)",
        files=(
            SourceFile(
                f"{RAW_GH}/pawelp0499/football-prediction-model/main/data/21_22.csv",
                "football_data_E0_2021_22.csv",
            ),
        ),
        closing_lines=True,
        starting_pitchers=False,
        license="football-data.co.uk data, free to use; repo unlicensed",
        quality="weak",
        notes="Proof that raw files with B365CH/PSCH closing columns exist on GitHub; only one league-season found.",
    ),
    SourceSpec(
        key="tennis_data_atp",
        sport="tennis",
        description="tennis-data.co.uk ATP yearly files mirrored in three repos (maxfar, ushinghal19, gmalbert)",
        seasons="2001-2026",
        files=_tennis(),
        closing_lines=False,
        starting_pitchers=False,
        license="tennis-data.co.uk (free for personal use); mirror repos unlicensed/MIT",
        quality="usable",
        notes=(
            "Winner/Loser odds from Bet365 (2002+), Pinnacle (2004+, gap 2009), Max/Avg (2010+). "
            "tennis-data does not document these as closing prices."
        ),
    ),
)


def source_by_key(key: str) -> SourceSpec:
    """Look up a catalog entry.

    Args:
        key: ``SourceSpec.key``.

    Returns:
        The matching spec.

    Raises:
        KeyError: If no source has that key.
    """
    for spec in SOURCES:
        if spec.key == key:
            return spec
    raise KeyError(key)


def source_paths(spec: SourceSpec, config: ParlayConfig) -> list[Path]:
    """Local paths for a source's files (whether or not downloaded)."""
    return [config.data_dir / spec.sport / f.filename for f in spec.files]


def download_source(
    spec: SourceSpec,
    config: ParlayConfig,
    refresh: bool = False,
    timeout: float = 300.0,
    session: requests.Session | None = None,
) -> list[Path]:
    """Download a source's files into ``<data_dir>/<sport>/``.

    Args:
        spec: Catalog entry.
        config: Provides ``data_dir``.
        refresh: Re-download files that already exist.
        timeout: Per-request timeout in seconds.
        session: Optional requests session (injectable for tests).

    Returns:
        Paths of all files (downloaded or pre-existing).

    Raises:
        ValueError: If a URL is not on an allowed GitHub host.
    """
    sess = session or requests.Session()
    out = []
    for f in spec.files:
        if not f.url.startswith(ALLOWED_URL_PREFIXES):
            raise ValueError(f"URL not on an allowed host: {f.url}")
        target = config.data_dir / spec.sport / f.filename
        if target.exists() and not refresh:
            out.append(target)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        resp = sess.get(f.url, timeout=timeout, stream=True)
        resp.raise_for_status()
        with open(target, "wb") as fh:
            for chunk in resp.iter_content(chunk_size=1 << 20):
                fh.write(chunk)
        out.append(target)
    return out


def inventory(config: ParlayConfig) -> pd.DataFrame:
    """Which catalog files exist locally, with sizes.

    Args:
        config: Provides ``data_dir``.

    Returns:
        One row per source: ``key, sport, n_files, n_present, bytes, quality``.
    """
    rows = []
    for spec in SOURCES:
        paths = source_paths(spec, config)
        present = [p for p in paths if p.exists()]
        rows.append(
            {
                "key": spec.key,
                "sport": spec.sport,
                "seasons": spec.seasons,
                "n_files": len(paths),
                "n_present": len(present),
                "bytes": int(sum(p.stat().st_size for p in present)),
                "closing_lines": spec.closing_lines,
                "starting_pitchers": spec.starting_pitchers,
                "quality": spec.quality,
            }
        )
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------- #
# Odds helpers
# --------------------------------------------------------------------------- #


def parse_line_value(value: Any) -> float:
    """Parse an SBR spread/total cell (``'pk'``, ``'NL'``, ``'237½'`` ...).

    Args:
        value: Raw cell content.

    Returns:
        Float, ``0.0`` for pick'em, ``NaN`` when no line was offered or the
        cell is unparsable.
    """
    if value is None:
        return math.nan
    if isinstance(value, (int, float, np.integer, np.floating)):
        return float(value)
    s = str(value).strip().replace("\xa0", "").replace(",", "")
    if not s:
        return math.nan
    low = s.lower()
    if low in {"pk", "p", "pick", "pk'"}:
        return 0.0
    if low in {"nl", "na", "n/a", "off", "-"}:
        return math.nan
    s = s.replace("½", ".5")
    try:
        return float(s)
    except ValueError:
        return math.nan


def parse_moneyline(value: Any) -> float:
    """Parse an American moneyline cell (``'ev'`` means ``+100``).

    Args:
        value: Raw cell content.

    Returns:
        Float odds or ``NaN``; a literal ``0`` is treated as missing.
    """
    if isinstance(value, str) and value.strip().lower() in {"ev", "even", "+ev"}:
        return 100.0
    v = parse_line_value(value)
    if v == 0.0:
        return math.nan
    return v


def american_to_prob(odds: pd.Series | np.ndarray | float) -> np.ndarray:
    """Implied (vig-inclusive) win probability of American odds (vectorised)."""
    o = np.asarray(odds, dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        p = np.where(o < 0, -o / (-o + 100.0), 100.0 / (o + 100.0))
    return np.where(np.isfinite(o), p, np.nan)


def american_hold(home_ml: pd.Series | np.ndarray, away_ml: pd.Series | np.ndarray) -> np.ndarray:
    """Bookmaker overround of a two-way moneyline: ``p_home + p_away - 1``."""
    return american_to_prob(home_ml) + american_to_prob(away_ml) - 1.0


def no_vig_home_prob(home_ml: pd.Series | np.ndarray, away_ml: pd.Series | np.ndarray) -> np.ndarray:
    """Home win probability after removing the vig proportionally."""
    ph = american_to_prob(home_ml)
    pa = american_to_prob(away_ml)
    return ph / (ph + pa)


def _blank_implausible(games: pd.DataFrame, sport: str) -> pd.DataFrame:
    rng = PLAUSIBLE.get(sport)
    if rng is None:
        return games
    for col in ("spread_open", "spread_close"):
        if col in games:
            v = games[col].to_numpy(dtype=float)
            bad = np.isfinite(v) & ((v < rng["spread"][0]) | (v > rng["spread"][1]))
            games.loc[bad, col] = np.nan
    for col in ("total_open", "total_close"):
        if col in games:
            v = games[col].to_numpy(dtype=float)
            bad = np.isfinite(v) & ((v < rng["total"][0]) | (v > rng["total"][1]))
            games.loc[bad, col] = np.nan
    return games


def _finish(games: pd.DataFrame, sport: str, source: str) -> pd.DataFrame:
    games = games.copy()
    games["sport"] = sport
    games["source"] = source
    for col in GAME_COLUMNS:
        if col not in games:
            games[col] = np.nan
    games["date"] = pd.to_datetime(games["date"], utc=True)
    games = _blank_implausible(games, sport)
    other = [c for c in games.columns if c not in GAME_COLUMNS]
    return games[GAME_COLUMNS + other].sort_values(["date", "home"]).reset_index(drop=True)


# --------------------------------------------------------------------------- #
# Team aliases
# --------------------------------------------------------------------------- #

NBA_ALIASES: dict[str, str] = {
    "NewJersey": "Nets",
    "New Jersey": "Nets",
    "Golden State": "Warriors",
    "GoldenState": "Warriors",
    "Seventysixers": "76ers",
    "Sixers": "76ers",
    "Trailblazers": "Trail Blazers",
}

NHL_ALIASES: dict[str, str] = {
    "Phoenix": "Coyotes",
    "Arizonas": "Coyotes",
    "Arizona": "Coyotes",
    "WinnipegJets": "Jets",
    "Tampa": "Lightning",
    "Tampa Bay": "Lightning",
    "NY Islanders": "Islanders",
    "SeattleKraken": "Kraken",
    "St.Louis": "Blues",
    "St. Louis": "Blues",
}

# SBR/FinnedAI and sportsbookreview shortName spellings -> Retrosheet codes.
# Season-dependent codes (Marlins FLO->MIA in 2012, Athletics OAK->ATH in 2025)
# are handled in mlb_retrosheet_code.
MLB_TEAM_CODES: dict[str, str] = {
    "Angels": "ANA",
    "LAA": "ANA",
    "Astros": "HOU",
    "HOU": "HOU",
    "Athletics": "OAK",
    "OAK": "OAK",
    "ATH": "OAK",
    "Blue Jays": "TOR",
    "TOR": "TOR",
    "Braves": "ATL",
    "ATL": "ATL",
    "Brewers": "MIL",
    "MIL": "MIL",
    "Cardinals": "SLN",
    "STL": "SLN",
    "Cubs": "CHN",
    "CUB": "CHN",
    "CHC": "CHN",
    "Diamondbacks": "ARI",
    "ARI": "ARI",
    "AZ": "ARI",
    "Dodgers": "LAN",
    "LOS": "LAN",
    "LAD": "LAN",
    "Giants": "SFN",
    "SFO": "SFN",
    "SF": "SFN",
    "Guardians": "CLE",
    "Indians": "CLE",
    "CLE": "CLE",
    "Mariners": "SEA",
    "SEA": "SEA",
    "Marlins": "MIA",
    "MIA": "MIA",
    "Mets": "NYN",
    "NYM": "NYN",
    "Nationals": "WAS",
    "WAS": "WAS",
    "WSH": "WAS",
    "Orioles": "BAL",
    "BAL": "BAL",
    "Padres": "SDN",
    "SDG": "SDN",
    "SD": "SDN",
    "Phillies": "PHI",
    "PHI": "PHI",
    "Pirates": "PIT",
    "PIT": "PIT",
    "Rangers": "TEX",
    "TEX": "TEX",
    "Rays": "TBA",
    "TAM": "TBA",
    "TB": "TBA",
    "Red Sox": "BOS",
    "BOS": "BOS",
    "Reds": "CIN",
    "CIN": "CIN",
    "Rockies": "COL",
    "COL": "COL",
    "Royals": "KCA",
    "KAN": "KCA",
    "KC": "KCA",
    "Tigers": "DET",
    "DET": "DET",
    "Twins": "MIN",
    "MIN": "MIN",
    "White Sox": "CHA",
    "CHW": "CHA",
    "Yankees": "NYA",
    "NYY": "NYA",
}


def mlb_retrosheet_code(name: str, season: int) -> str | None:
    """Map an odds-file team spelling to the Retrosheet code used that season.

    Args:
        name: Team spelling from an SBR-derived file (``"LOS"``, ``"Red Sox"``, ``"NYY"``).
        season: Season year.

    Returns:
        Retrosheet team code, or ``None`` for unknown names (e.g. All-Star ``"AL"``).
    """
    code = MLB_TEAM_CODES.get(str(name).strip())
    if code == "MIA" and season <= 2011:
        return "FLO"
    if code == "OAK" and season >= 2025:
        return "ATH"
    return code


def normalize_team(name: Any, sport: str) -> str | None:
    """Canonical franchise nickname for NBA/NHL scrapes; passthrough otherwise.

    Args:
        name: Raw team string.
        sport: Sport key.

    Returns:
        Canonical name, or ``None`` for junk rows (``'0'``, blank, NaN).
    """
    if name is None or (isinstance(name, float) and math.isnan(name)):
        return None
    s = str(name).strip()
    if s in {"", "0", "nan"}:
        return None
    if sport == "nba":
        return NBA_ALIASES.get(s, s)
    if sport == "nhl":
        return NHL_ALIASES.get(s, s)
    return s


# --------------------------------------------------------------------------- #
# SBR season workbooks (two rows per game)
# --------------------------------------------------------------------------- #


def sbr_season_years(dates_mmdd: pd.Series, start_year: int) -> np.ndarray:
    """Assign calendar years to SBR ``MMDD`` dates by month rollover.

    Rows are in chronological order; whenever the month decreases the year is
    incremented. This handles the 2019-20 NBA bubble (Oct 2019 to Oct 2020)
    correctly, unlike a fixed "month >= 8" rule.

    Args:
        dates_mmdd: Integer-like ``MMDD`` values in file order.
        start_year: First calendar year of the season label (``2007`` for ``2007-08``).

    Returns:
        Calendar year per row.
    """
    d = pd.to_numeric(dates_mmdd, errors="coerce").to_numpy(dtype=float)
    month = np.floor(d / 100.0)
    prev = np.roll(month, 1)
    prev[0] = month[0]
    wrap = np.where(np.isfinite(month) & np.isfinite(prev), month < prev, False)
    return start_year + np.cumsum(wrap.astype(int))


def _split_spread_total(v_val: float, h_val: float, threshold: float) -> tuple[float, float]:
    """Interpret the visitor/home Open-or-Close cells as (expected home margin, total)."""
    v_ok, h_ok = math.isfinite(v_val), math.isfinite(h_val)
    if v_ok and h_ok:
        if v_val > h_val:
            return h_val, v_val  # visitor row holds the total, home is favourite
        if h_val > v_val:
            return -v_val, h_val  # home row holds the total, visitor is favourite
        return (math.nan, v_val) if v_val >= threshold else (0.0, math.nan)
    if v_ok:
        return (math.nan, v_val) if v_val >= threshold else (-v_val, math.nan)
    if h_ok:
        return (math.nan, h_val) if h_val >= threshold else (h_val, math.nan)
    return math.nan, math.nan


def sbr_rows_to_games(rows: pd.DataFrame, sport: str, start_year: int, source: str = "sbr_xlsx") -> pd.DataFrame:
    """Convert an SBR two-rows-per-game sheet into one row per game.

    Args:
        rows: Sheet with columns ``Date, VH, Team, Final, Open, Close, ML`` in
            file order (visitor row first, then home; ``VH == 'N'`` for neutral).
        sport: Sport key (selects the total/spread threshold and plausibility range).
        start_year: First calendar year of the season label.
        source: Value for the ``source`` column.

    Returns:
        Games in ``GAME_COLUMNS`` layout. ``spread_*`` is the expected
        ``home - away`` margin; pick'em is ``0.0``; no line is ``NaN``.
    """
    df = rows.reset_index(drop=True)
    n = len(df) - (len(df) % 2)
    df = df.iloc[:n]
    v = df.iloc[0::2].reset_index(drop=True)
    h = df.iloc[1::2].reset_index(drop=True)
    valid = (v["VH"].astype(str).str.upper().isin(["V", "N"])) & (h["VH"].astype(str).str.upper().isin(["H", "N"]))
    v, h = v[valid].reset_index(drop=True), h[valid].reset_index(drop=True)
    years = sbr_season_years(v["Date"], start_year)
    mmdd = pd.to_numeric(v["Date"], errors="coerce")
    dates = pd.to_datetime(
        pd.Series(years).astype(int).astype(str) + mmdd.astype("Int64").astype(str).str.zfill(4),
        format="%Y%m%d",
        errors="coerce",
        utc=True,
    )
    thr = SBR_TOTAL_THRESHOLD.get(sport, 100.0)
    spread_open, total_open, spread_close, total_close = [], [], [], []
    for ov, oh, cv, ch in zip(
        v["Open"].map(parse_line_value),
        h["Open"].map(parse_line_value),
        v["Close"].map(parse_line_value),
        h["Close"].map(parse_line_value),
    ):
        so, to = _split_spread_total(ov, oh, thr)
        sc, tc = _split_spread_total(cv, ch, thr)
        spread_open.append(so)
        total_open.append(to)
        spread_close.append(sc)
        total_close.append(tc)
    games = pd.DataFrame(
        {
            "season": start_year,
            "date": dates,
            "home": h["Team"].astype(str).str.strip(),
            "away": v["Team"].astype(str).str.strip(),
            "neutral": v["VH"].astype(str).str.upper().eq("N"),
            "home_score": pd.to_numeric(h["Final"], errors="coerce"),
            "away_score": pd.to_numeric(v["Final"], errors="coerce"),
            "home_ml_close": h["ML"].map(parse_moneyline),
            "away_ml_close": v["ML"].map(parse_moneyline),
            "spread_open": spread_open,
            "spread_close": spread_close,
            "total_open": total_open,
            "total_close": total_close,
        }
    )
    games = games[games["date"].notna()]
    return _finish(games, sport, source)


def read_sbr_xlsx(path: Path, sport: str, start_year: int) -> pd.DataFrame:
    """Read one SBR season workbook (first sheet) into games.

    Args:
        path: ``.xlsx`` file (requires ``openpyxl``).
        sport: Sport key.
        start_year: First calendar year of the season label.

    Returns:
        See :func:`sbr_rows_to_games`.
    """
    rows = pd.read_excel(path, sheet_name=0)
    return sbr_rows_to_games(rows, sport, start_year, source="sbr_xlsx")


def sbr_start_year(path: Path) -> int:
    """Season start year from a filename like ``nba_odds_2015-16.xlsx``."""
    stem = Path(path).stem
    return int(stem.rsplit("_", 1)[-1].split("-")[0])


# --------------------------------------------------------------------------- #
# FinnedAI JSON archives
# --------------------------------------------------------------------------- #


def finned_to_games(records: pd.DataFrame, sport: str, source: str = "sbr_finned") -> pd.DataFrame:
    """Normalise a FinnedAI ``<sport>_archive_10Y.json`` table.

    Args:
        records: ``pd.read_json`` of the archive (one row per game).
        sport: ``mlb``, ``nba``, ``nhl`` or ``nfl``.
        source: Value for the ``source`` column.

    Returns:
        Games in ``GAME_COLUMNS`` layout. Rows with junk team names (``'0'``)
        or missing dates are dropped; zero moneylines/run lines become NaN.
    """
    df = records.copy()
    df["home"] = df["home_team"].map(lambda x: normalize_team(x, sport))
    df["away"] = df["away_team"].map(lambda x: normalize_team(x, sport))
    df = df[df["home"].notna() & df["away"].notna() & df["date"].notna()].copy()
    df["date"] = pd.to_datetime(df["date"].astype(int).astype(str), format="%Y%m%d", errors="coerce", utc=True)
    df = df[df["date"].notna()]
    out = pd.DataFrame(
        {
            "season": df["season"].astype(int),
            "date": df["date"],
            "home": df["home"],
            "away": df["away"],
            "neutral": False,
            "home_score": pd.to_numeric(df.get("home_final"), errors="coerce"),
            "away_score": pd.to_numeric(df.get("away_final"), errors="coerce"),
        },
        index=df.index,
    )
    for col, src in (
        ("home_ml_open", "home_open_ml"),
        ("away_ml_open", "away_open_ml"),
        ("home_ml_close", "home_close_ml"),
        ("away_ml_close", "away_close_ml"),
    ):
        out[col] = pd.to_numeric(df[src], errors="coerce").replace(0.0, np.nan) if src in df else np.nan
    for col, src in (("spread_open", "home_open_spread"), ("spread_close", "home_close_spread")):
        if src in df:
            s = -pd.to_numeric(df[src], errors="coerce")
            if sport in {"mlb", "nhl"}:
                s = s.replace(-0.0, np.nan).replace(0.0, np.nan)  # run/puck line 0.0 means missing
            out[col] = s
        else:
            out[col] = np.nan
    for col, src in (("total_open", "open_over_under"), ("total_close", "close_over_under")):
        out[col] = pd.to_numeric(df[src], errors="coerce").replace(0.0, np.nan) if src in df else np.nan
    for col in ("home_close_spread_odds", "away_close_spread_odds", "open_over_under_odds", "close_over_under_odds"):
        if col in df:
            out[col] = pd.to_numeric(df[col], errors="coerce").replace(0.0, np.nan)
    return _finish(out, sport, source)


def read_finned_json(path: Path, sport: str) -> pd.DataFrame:
    """Read a FinnedAI archive file into games."""
    return finned_to_games(pd.read_json(path), sport)


# --------------------------------------------------------------------------- #
# sportsbookreview per-book JSON (ArnavSaraogi release asset)
# --------------------------------------------------------------------------- #

DEFAULT_BOOK_PREFERENCE = ("bet365", "draftkings", "fanduel", "caesars", "betmgm", "bet_rivers_ny")


def _pick_book(entries: list[dict[str, Any]], preference: tuple[str, ...]) -> tuple[dict[str, Any] | None, str | None]:
    by_book = {e.get("sportsbook"): e for e in entries}
    for b in preference:
        if b in by_book:
            return by_book[b], b
    return None, None


def sbr_book_records_to_games(
    data: dict[str, list[dict[str, Any]]],
    book_preference: tuple[str, ...] = DEFAULT_BOOK_PREFERENCE,
    game_types: tuple[str, ...] | None = ("R",),
) -> pd.DataFrame:
    """Flatten the nested per-book MLB JSON into one row per game.

    Args:
        data: Mapping ``"YYYY-MM-DD" -> [game dicts]`` with ``gameView`` and
            ``odds.moneyline/pointspread/totals`` lists per sportsbook.
        book_preference: First available book in this order supplies the lines.
        game_types: Keep only these ``gameView.gameType`` values (``"R"`` regular
            season). ``None`` keeps everything.

    Returns:
        Games in ``GAME_COLUMNS`` layout with extra ``book``, ``n_books``,
        ``game_type``, ``status``, ``spread_close_home_odds`` and
        ``total_close_over_odds`` columns. ``currentLine`` is the last captured
        price, i.e. the closing line for completed games.
    """
    rows = []
    for day, games in data.items():
        for g in games:
            gv = g.get("gameView", {})
            od = g.get("odds", {})
            gtype = gv.get("gameType")
            if game_types is not None and gtype not in game_types:
                continue
            status = str(gv.get("gameStatusText", ""))
            if status.lower().startswith("postponed"):
                continue
            home = (gv.get("homeTeam") or {}).get("shortName")
            away = (gv.get("awayTeam") or {}).get("shortName")
            if home in {"AL", "NL"} or away in {"AL", "NL"}:
                continue
            ml, mb = _pick_book(od.get("moneyline", []), book_preference)
            sp, _ = _pick_book(od.get("pointspread", []), book_preference)
            tt, _ = _pick_book(od.get("totals", []), book_preference)
            ml_o = (ml or {}).get("openingLine", {}) or {}
            ml_c = (ml or {}).get("currentLine", {}) or {}
            sp_o = (sp or {}).get("openingLine", {}) or {}
            sp_c = (sp or {}).get("currentLine", {}) or {}
            tt_o = (tt or {}).get("openingLine", {}) or {}
            tt_c = (tt or {}).get("currentLine", {}) or {}
            hs = sp_c.get("homeSpread")
            hso = sp_o.get("homeSpread")
            rows.append(
                {
                    "season": int(day[:4]),
                    "date": day,
                    "home": home,
                    "away": away,
                    "neutral": False,
                    "home_score": gv.get("homeTeamScore"),
                    "away_score": gv.get("awayTeamScore"),
                    "home_ml_open": ml_o.get("homeOdds"),
                    "away_ml_open": ml_o.get("awayOdds"),
                    "home_ml_close": ml_c.get("homeOdds"),
                    "away_ml_close": ml_c.get("awayOdds"),
                    "spread_open": -hso if hso is not None else np.nan,
                    "spread_close": -hs if hs is not None else np.nan,
                    "spread_close_home_odds": sp_c.get("homeOdds"),
                    "spread_close_away_odds": sp_c.get("awayOdds"),
                    "total_open": tt_o.get("total"),
                    "total_close": tt_c.get("total"),
                    "total_close_over_odds": tt_c.get("overOdds"),
                    "total_close_under_odds": tt_c.get("underOdds"),
                    "book": mb,
                    "n_books": len(od.get("moneyline", [])),
                    "game_type": gtype,
                    "status": status,
                    "start_utc": gv.get("startDate"),
                }
            )
    out = pd.DataFrame(rows)
    for c in ("home_score", "away_score", "home_ml_open", "away_ml_open", "home_ml_close", "away_ml_close",
              "spread_open", "spread_close", "total_open", "total_close"):
        out[c] = pd.to_numeric(out[c], errors="coerce")
    return _finish(out, "mlb", "sbr_book")


def read_sbr_book_json(path: Path, **kwargs: Any) -> pd.DataFrame:
    """Read the per-book MLB JSON release asset into games."""
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    return sbr_book_records_to_games(data, **kwargs)


# --------------------------------------------------------------------------- #
# Retrosheet game logs
# --------------------------------------------------------------------------- #

RETROSHEET_FIELDS: dict[str, int] = {
    "date": 0,
    "game_number": 1,
    "away": 3,
    "home": 6,
    "away_score": 9,
    "home_score": 10,
    "day_night": 12,
    "park": 16,
    "away_pitcher_id": 101,
    "away_pitcher": 102,
    "home_pitcher_id": 103,
    "home_pitcher": 104,
}


def retrosheet_gamelog_to_games(raw: pd.DataFrame) -> pd.DataFrame:
    """Extract results and starting pitchers from a Retrosheet game log.

    Args:
        raw: ``pd.read_csv(path, header=None)`` of a ``GLyyyy.TXT`` file (161 fields).

    Returns:
        ``date`` (UTC), ``season``, ``game_number`` (0 single, 1/2 doubleheader),
        ``home``, ``away`` (Retrosheet codes), scores, ``park``, ``day_night`` and
        ``home/away_pitcher_id`` + ``home/away_pitcher`` names.
    """
    out = pd.DataFrame({k: raw.iloc[:, i] for k, i in RETROSHEET_FIELDS.items()})
    out["date"] = pd.to_datetime(out["date"].astype(str), format="%Y%m%d", utc=True)
    out["season"] = out["date"].dt.year
    out["game_number"] = pd.to_numeric(out["game_number"], errors="coerce").fillna(0).astype(int)
    out["home_score"] = pd.to_numeric(out["home_score"], errors="coerce")
    out["away_score"] = pd.to_numeric(out["away_score"], errors="coerce")
    return out.reset_index(drop=True)


def read_retrosheet_gamelog(path: Path) -> pd.DataFrame:
    """Read one ``GLyyyy.TXT`` file."""
    return retrosheet_gamelog_to_games(pd.read_csv(path, header=None, low_memory=False))


def attach_starting_pitchers(games: pd.DataFrame, gamelogs: pd.DataFrame) -> pd.DataFrame:
    """Join Retrosheet starting pitchers onto MLB odds rows.

    Match on (calendar date, home code, away code); doubleheaders are
    disambiguated by final score. A game that still matches several log rows
    (identical scores) or none is left without pitchers.

    Args:
        games: Odds rows with ``season, date, home, away, home_score, away_score``;
            team spellings are mapped with :func:`mlb_retrosheet_code`.
        gamelogs: Output of :func:`retrosheet_gamelog_to_games` (any seasons).

    Returns:
        ``games`` with ``home_code, away_code, home_pitcher_id, home_pitcher,
        away_pitcher_id, away_pitcher, retro_game_number`` and a boolean
        ``pitcher_match`` column.
    """
    g = games.copy()
    g["_ix"] = np.arange(len(g))
    g["home_code"] = [mlb_retrosheet_code(t, s) for t, s in zip(g["home"], g["season"])]
    g["away_code"] = [mlb_retrosheet_code(t, s) for t, s in zip(g["away"], g["season"])]
    g["_day"] = pd.to_datetime(g["date"], utc=True).dt.strftime("%Y-%m-%d")
    gl = gamelogs.copy()
    gl["_day"] = pd.to_datetime(gl["date"], utc=True).dt.strftime("%Y-%m-%d")
    gl = gl.rename(columns={"home": "home_code", "away": "away_code", "home_score": "_gl_hs", "away_score": "_gl_as"})
    cols = ["_day", "home_code", "away_code", "_gl_hs", "_gl_as", "game_number",
            "home_pitcher_id", "home_pitcher", "away_pitcher_id", "away_pitcher"]
    m = g[["_ix", "_day", "home_code", "away_code", "home_score", "away_score"]].merge(
        gl[cols], on=["_day", "home_code", "away_code"], how="inner"
    )
    have_scores = m["home_score"].notna() & m["away_score"].notna()
    score_ok = (m["home_score"] == m["_gl_hs"]) & (m["away_score"] == m["_gl_as"])
    m = m[~have_scores | score_ok]
    counts = m.groupby("_ix").size()
    unique_ix = counts[counts == 1].index
    m = m[m["_ix"].isin(unique_ix)].set_index("_ix")
    for col in ("home_pitcher_id", "home_pitcher", "away_pitcher_id", "away_pitcher"):
        g[col] = g["_ix"].map(m[col])
    g["retro_game_number"] = g["_ix"].map(m["game_number"])
    g["pitcher_match"] = g["home_pitcher_id"].notna()
    return g.drop(columns=["_ix", "_day"])


def repair_finned_mlb(records: pd.DataFrame, gamelogs: pd.DataFrame) -> pd.DataFrame:
    """Rebuild real MLB games from the scrambled FinnedAI MLB archive.

    In ``mlb_archive_10Y.json`` each row pairs two teams that played in
    *different* games that day (no row matches a Retrosheet matchup, but each
    team's own score and moneyline are intact). This splits every row into two
    team records, attaches each record to its true Retrosheet game via
    ``(date, team)`` (doubleheaders resolved by score) and re-assembles games
    from the two records that landed on the same Retrosheet game.

    Game-level fields that cannot be attributed to a team (totals) are taken
    from the row containing the true *away* team: on the 2021 overlap with the
    per-book file that row's total equals bet365's closing total 74% of the
    time (94% within half a run) while the home team's row is no better than a
    shuffle. ``total_close_home_row`` is kept for diagnostics.

    Args:
        records: ``pd.read_json`` of the FinnedAI MLB archive.
        gamelogs: Output of :func:`retrosheet_gamelog_to_games` covering the seasons.

    Returns:
        Games in ``GAME_COLUMNS`` layout (teams as Retrosheet codes, scores from
        Retrosheet, starting pitchers attached) plus ``home_ml_source_row``,
        ``away_ml_source_row`` and ``retro_game_number``.
    """
    raw = records[records["date"].notna()].copy()
    raw["_day"] = pd.to_datetime(raw["date"].astype(int).astype(str), format="%Y%m%d", errors="coerce").dt.strftime("%Y-%m-%d")
    raw = raw[raw["_day"].notna()].reset_index(drop=True)
    raw["_row"] = np.arange(len(raw))
    parts = []
    for side in ("home", "away"):
        part = pd.DataFrame(
            {
                "_row": raw["_row"],
                "_day": raw["_day"],
                "season": raw["season"].astype(int),
                "team": raw[f"{side}_team"].astype(str),
                "score": pd.to_numeric(raw[f"{side}_final"], errors="coerce"),
                "ml_close": pd.to_numeric(raw[f"{side}_close_ml"], errors="coerce").replace(0.0, np.nan),
                "ml_open": pd.to_numeric(raw[f"{side}_open_ml"], errors="coerce").replace(0.0, np.nan),
                "run_line": pd.to_numeric(raw[f"{side}_close_spread"], errors="coerce").replace(0.0, np.nan),
                "run_line_odds": pd.to_numeric(raw[f"{side}_close_spread_odds"], errors="coerce").replace(0.0, np.nan),
                "total_close": pd.to_numeric(raw["close_over_under"], errors="coerce").replace(0.0, np.nan),
                "total_open": pd.to_numeric(raw["open_over_under"], errors="coerce").replace(0.0, np.nan),
            }
        )
        parts.append(part)
    recs = pd.concat(parts, ignore_index=True)
    recs["code"] = [mlb_retrosheet_code(t, s) for t, s in zip(recs["team"], recs["season"])]
    recs = recs[recs["code"].notna()]
    gl = gamelogs.reset_index(drop=True).copy()
    gl["_gid"] = np.arange(len(gl))
    gl["_day"] = pd.to_datetime(gl["date"], utc=True).dt.strftime("%Y-%m-%d")
    team_games = pd.concat(
        [
            pd.DataFrame({"_gid": gl["_gid"], "_day": gl["_day"], "code": gl["home"], "is_home": True, "rs_score": gl["home_score"]}),
            pd.DataFrame({"_gid": gl["_gid"], "_day": gl["_day"], "code": gl["away"], "is_home": False, "rs_score": gl["away_score"]}),
        ],
        ignore_index=True,
    )
    m = recs.merge(team_games, on=["_day", "code"], how="inner")
    m["_rec"] = m["_row"].astype(str) + m["team"]
    n_cand = m.groupby("_rec")["_gid"].transform("size")
    m = m[(n_cand == 1) | (m["score"] == m["rs_score"])]
    n_cand = m.groupby("_rec")["_gid"].transform("size")
    m = m[n_cand == 1]
    # One record per (game, side); if a team appears twice for the same game keep the first.
    m = m.sort_values(["_gid", "is_home", "_row"]).drop_duplicates(["_gid", "is_home"])
    home = m[m["is_home"]].set_index("_gid")
    away = m[~m["is_home"]].set_index("_gid")
    both = home.index.intersection(away.index)
    h = home.loc[both]
    a = away.loc[both]
    g = gl.set_index("_gid").loc[both]
    run_line_home = -h["run_line"]
    spread_close = run_line_home.where(run_line_home.notna(), a["run_line"])
    out = pd.DataFrame(
        {
            "season": g["season"].to_numpy(),
            "date": g["date"].to_numpy(),
            "home": g["home"].to_numpy(),
            "away": g["away"].to_numpy(),
            "neutral": False,
            "home_score": g["home_score"].to_numpy(),
            "away_score": g["away_score"].to_numpy(),
            "home_ml_open": h["ml_open"].to_numpy(),
            "away_ml_open": a["ml_open"].to_numpy(),
            "home_ml_close": h["ml_close"].to_numpy(),
            "away_ml_close": a["ml_close"].to_numpy(),
            "spread_open": np.nan,
            "spread_close": spread_close.to_numpy(),
            "spread_close_home_odds": h["run_line_odds"].to_numpy(),
            "spread_close_away_odds": a["run_line_odds"].to_numpy(),
            "total_open": a["total_open"].to_numpy(),
            "total_close": a["total_close"].to_numpy(),
            "total_close_home_row": h["total_close"].to_numpy(),
            "home_pitcher_id": g["home_pitcher_id"].to_numpy(),
            "away_pitcher_id": g["away_pitcher_id"].to_numpy(),
            "home_pitcher": g["home_pitcher"].to_numpy(),
            "away_pitcher": g["away_pitcher"].to_numpy(),
            "retro_game_number": g["game_number"].to_numpy(),
            "home_ml_source_row": h["_row"].to_numpy(),
            "away_ml_source_row": a["_row"].to_numpy(),
        }
    )
    return _finish(out, "mlb", "sbr_finned_repaired")


# --------------------------------------------------------------------------- #
# Tennis (tennis-data.co.uk yearly files)
# --------------------------------------------------------------------------- #

TENNIS_KEEP = [
    "ATP", "Location", "Tournament", "Date", "Series", "Court", "Surface", "Round", "Best of",
    "Winner", "Loser", "WRank", "LRank", "Wsets", "Lsets", "Comment",
    "B365W", "B365L", "PSW", "PSL", "MaxW", "MaxL", "AvgW", "AvgL",
]


def parse_mixed_dates(values: pd.Series) -> pd.Series:
    """Parse date strings whose format differs between mirror files.

    tennis-data mirrors use ``dd/mm/yyyy`` (original) or ``mm/dd/yyyy``
    (re-exported). Each candidate format is tried on the whole column and the
    one that parses the most rows wins, so a file is never read with a mix.

    Args:
        values: Date strings (or datetimes, returned unchanged).

    Returns:
        Naive datetimes with ``NaT`` where nothing parsed.
    """
    if pd.api.types.is_datetime64_any_dtype(values):
        return pd.to_datetime(values)
    best: pd.Series | None = None
    best_n = -1
    for fmt in ("%d/%m/%Y", "%m/%d/%Y", "%Y-%m-%d", "%d/%m/%y", "%m/%d/%y"):
        parsed = pd.to_datetime(values.astype(str).str.strip(), format=fmt, errors="coerce")
        n = int(parsed.notna().sum())
        if n > best_n:
            best, best_n = parsed, n
    assert best is not None
    return best


def tennis_rows_to_matches(df: pd.DataFrame) -> pd.DataFrame:
    """Normalise a tennis-data.co.uk yearly table.

    Args:
        df: Raw CSV/XLSX table (columns may be a subset of ``TENNIS_KEEP``).

    Returns:
        Kept columns with ``Date`` parsed (day-first strings or datetimes),
        ``year`` and ``winner_favourite`` (Pinnacle where available, else Bet365).
    """
    cols = [c for c in TENNIS_KEEP if c in df.columns]
    out = df[cols].copy()
    if not pd.api.types.is_datetime64_any_dtype(out["Date"]):
        out["Date"] = parse_mixed_dates(out["Date"])
    out["Date"] = pd.to_datetime(out["Date"], utc=True)
    out = out[out["Date"].notna()]
    out["year"] = out["Date"].dt.year
    for c in ("B365W", "B365L", "PSW", "PSL", "MaxW", "MaxL", "AvgW", "AvgL", "WRank", "LRank"):
        if c in out:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    w = out["PSW"] if "PSW" in out else pd.Series(np.nan, index=out.index)
    l = out["PSL"] if "PSL" in out else pd.Series(np.nan, index=out.index)
    if "B365W" in out:
        w = w.fillna(out["B365W"])
        l = l.fillna(out["B365L"])
    out["winner_favourite"] = np.where(w.notna() & l.notna(), w < l, np.nan)
    return out.reset_index(drop=True)


def read_tennis_data(path: Path) -> pd.DataFrame:
    """Read a yearly tennis-data file (``.csv`` latin-1 or ``.xlsx``)."""
    path = Path(path)
    if path.suffix.lower() == ".xlsx":
        df = pd.read_excel(path, sheet_name=0)
    else:
        df = pd.read_csv(path, encoding="latin-1", low_memory=False)
    return tennis_rows_to_matches(df)


# --------------------------------------------------------------------------- #
# Bridge to the existing NFL pipeline
# --------------------------------------------------------------------------- #


def to_nflverse_layout(games: pd.DataFrame, market: str = "spread") -> pd.DataFrame:
    """Re-shape ``GAME_COLUMNS`` games into the nflverse table ``clean_games`` expects.

    ``week`` becomes the week index within the season (from the first game
    date), ``game_type`` is ``"REG"`` and starting-pitcher ids are placed in
    ``home_qb_id`` / ``away_qb_id`` so the "new QB" logic doubles as a
    "new starting pitcher" flag.

    Args:
        games: Output of any parser in this module.
        market: ``"spread"`` keeps ``result = home - away`` versus
            ``spread_line = spread_close``. ``"moneyline"`` sets
            ``result = 1[home win] - p_home`` (no-vig closing probability) and
            ``spread_line = 0`` so that the residual is the moneyline surprise.

    Returns:
        Table with the nflverse columns used by ``geo_model.parlay.data``.

    Raises:
        ValueError: On an unknown ``market``.
    """
    g = games.copy()
    g = g[g["home_score"].notna() & g["away_score"].notna()]
    if market == "spread":
        result = g["home_score"] - g["away_score"]
        spread_line = g["spread_close"]
    elif market == "moneyline":
        p_home = no_vig_home_prob(g["home_ml_close"], g["away_ml_close"])
        home_win = np.where(g["home_score"] > g["away_score"], 1.0, np.where(g["home_score"] < g["away_score"], 0.0, np.nan))
        result = pd.Series(home_win - p_home, index=g.index)
        spread_line = pd.Series(np.where(np.isfinite(p_home), 0.0, np.nan), index=g.index)
    else:
        raise ValueError(f"unknown market {market!r}")
    first = g.groupby("season")["date"].transform("min")
    week = ((g["date"] - first).dt.days // 7 + 1).astype(int)
    out = pd.DataFrame(
        {
            "season": g["season"].astype(int),
            "game_type": "REG",
            "week": week,
            "gameday": g["date"].dt.strftime("%Y-%m-%d"),
            "home_team": g["home"],
            "away_team": g["away"],
            "home_score": g["home_score"],
            "away_score": g["away_score"],
            "result": result,
            "total": g["home_score"] + g["away_score"],
            "spread_line": spread_line,
            "total_line": g["total_close"],
            "home_moneyline": g["home_ml_close"],
            "away_moneyline": g["away_ml_close"],
            "home_qb_id": g["home_pitcher_id"] if "home_pitcher_id" in g else np.nan,
            "away_qb_id": g["away_pitcher_id"] if "away_pitcher_id" in g else np.nan,
        },
        index=g.index,
    )
    out["game_id"] = out["gameday"].str.replace("-", "_") + "_" + out["away_team"].astype(str) + "_" + out["home_team"].astype(str)
    dup = out.groupby("game_id").cumcount()
    out.loc[dup > 0, "game_id"] = out.loc[dup > 0, "game_id"] + "_g" + (dup[dup > 0] + 1).astype(str)
    return out.reset_index(drop=True)


# --------------------------------------------------------------------------- #
# Convenience loaders over the local cache
# --------------------------------------------------------------------------- #


def load_sbr_xlsx_sport(sport: str, config: ParlayConfig) -> pd.DataFrame:
    """Concatenate all cached SBR workbooks for a sport."""
    spec = source_by_key(f"{sport}_sbr_xlsx")
    frames = [read_sbr_xlsx(p, sport, sbr_start_year(p)) for p in source_paths(spec, config) if p.exists()]
    if not frames:
        return pd.DataFrame(columns=GAME_COLUMNS)
    return pd.concat(frames, ignore_index=True)


def load_retrosheet_gamelogs(config: ParlayConfig) -> pd.DataFrame:
    """Concatenate all cached Retrosheet game logs."""
    spec = source_by_key("mlb_retrosheet_gamelogs")
    frames = [read_retrosheet_gamelog(p) for p in source_paths(spec, config) if p.exists()]
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def load_tennis(config: ParlayConfig) -> pd.DataFrame:
    """Concatenate all cached tennis-data yearly files."""
    spec = source_by_key("tennis_data_atp")
    frames = [read_tennis_data(p) for p in source_paths(spec, config) if p.exists()]
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)
