"""Run the cross-game correlated-parlay backtest and write a markdown report.

Usage:
    python scripts/backtest_parlay.py [--refresh] [--out docs/experiments/parlay-interaction-effects.md]

Data location is controlled by ``GEO_MODEL_DATA_DIR`` (default ``data/raw``).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from geo_model.parlay import (
    KalmanParams,
    MarketErrorKalman,
    ParlayConfig,
    breakeven_correlation,
    build_shared_game_pairs,
    correlation_summary,
    load_games,
    parlay_ev,
    to_team_games,
    two_sided_parlay_roi,
)
from geo_model.parlay.backtest import (
    gaussian_explaining_away_corr,
    kalman_pair_calibration,
    kalman_slope,
)
from geo_model.parlay.kalman import simulate_games
from geo_model.parlay.pairs import stratify

TRAIN_SEASONS_END = 2009


def md_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub markdown table."""
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.astype(object).iterrows():
        lines.append("| " + " | ".join(_fmt(v) for v in r.tolist()) + " |")
    return "\n".join(lines)


def _fmt(v: object) -> str:
    if isinstance(v, float):
        return f"{v:.4f}" if abs(v) < 10 else f"{v:.1f}"
    return str(v)


def summary_rows(groups: dict[str, tuple[pd.Series, pd.Series]]) -> pd.DataFrame:
    """Correlation summaries for a dict of labeled (x, y) leg pairs."""
    rows = []
    for label, (x, y) in groups.items():
        row = {"subset": label}
        row.update(correlation_summary(x, y).to_row())
        rows.append(row)
    return pd.DataFrame(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--refresh", action="store_true", help="re-download the games file")
    ap.add_argument("--out", default="docs/experiments/parlay-interaction-effects.md")
    args = ap.parse_args()

    cfg = ParlayConfig()
    games = load_games(cfg, refresh=args.refresh)
    tg = to_team_games(games, cfg)
    pairs = build_shared_game_pairs(tg)
    d = cfg.leg_decimal
    be = breakeven_correlation(d)

    out: list[str] = []
    out.append("# Cross-game correlated parlays: backtest\n")
    out.append(
        "Hypothesis: a surprising result has competing explanations (team H better than "
        "priced vs. team A worse than priced). Conditioning on the shared game should make "
        "the market's errors on H and A positively correlated, so H's and A's *next* games "
        "(against different opponents, priced independently) have correlated spread "
        "residuals. Books price non-same-game parlays as independent, so a large enough "
        "correlation would make such parlays +EV.\n"
    )
    out.append(f"Generated by `scripts/backtest_parlay.py`. Data: nflverse games file, "
               f"seasons {cfg.seasons[0]}–{cfg.seasons[1]}, {cfg.game_types} games, "
               f"{len(games)} games, {len(pairs)} shared-game leg pairs.\n")

    # 1. Pricing hurdle
    out.append("## 1. What correlation is needed\n")
    out.append(
        f"At {cfg.leg_odds_american:+.0f} per leg (decimal {d:.3f}) a 2-leg parlay pays "
        f"{d**2:.3f}. With 50/50 legs the phi correlation between the two leg-win "
        f"indicators must exceed **{be:.3f}** just to break even. "
        f"For reference: EV at rho=0 is {parlay_ev(0, d):+.3f} per unit; at rho=0.05 it is "
        f"{parlay_ev(0.05, d):+.3f}; at rho=0.15 it is {parlay_ev(0.15, d):+.3f}.\n"
    )

    # 2. Shared-game pairs
    out.append("## 2. Shared-game pairs (H's next game vs. A's next game)\n")
    out.append(
        "`pearson`/`phi` are the correlation of the two next-game residuals (continuous / "
        "cover indicators). Prediction: **positive** for spreads, **negative** for totals. "
        "`p_both` is the empirical joint-cover rate vs. `p_indep` under independence.\n"
    )
    sb = stratify(pairs, "abs_surprise", cfg.surprise_bins)
    spread_groups: dict[str, tuple[pd.Series, pd.Series]] = {
        "all": (pairs["h_next_resid"], pairs["a_next_resid"]),
    }
    for lab in sorted(sb.unique()):
        m = sb == lab
        spread_groups[f"|surprise| {lab}"] = (pairs.loc[m, "h_next_resid"], pairs.loc[m, "a_next_resid"])
    for lab, m in {
        "new QB on either team": pairs["new_qb_any"],
        "no new QB": ~pairs["new_qb_any"],
        "weeks 1-4": pairs["week"] <= 4,
        "weeks 5+": pairs["week"] > 4,
        "both next games same week": pairs["same_next_week"],
        "2010+": pairs["season"] >= 2010,
    }.items():
        spread_groups[lab] = (pairs.loc[m, "h_next_resid"], pairs.loc[m, "a_next_resid"])
    out.append("### Spread residuals\n")
    out.append(md_table(summary_rows(spread_groups)) + "\n")

    total_groups = {
        "all": (pairs["h_next_tresid"], pairs["a_next_tresid"]),
        "|total surprise| >= 10": (
            pairs.loc[pairs["anchor_tresid"].abs() >= 10, "h_next_tresid"],
            pairs.loc[pairs["anchor_tresid"].abs() >= 10, "a_next_tresid"],
        ),
        "weeks 1-4": (pairs.loc[pairs["week"] <= 4, "h_next_tresid"], pairs.loc[pairs["week"] <= 4, "a_next_tresid"]),
    }
    out.append("### Total residuals\n")
    out.append(md_table(summary_rows(total_groups)) + "\n")

    # Cross term: does anchor surprise direction interact? (sign-conditioned)
    out.append("### Sign-conditioned view\n")
    out.append(
        "Product of next-game cover signs, split by who 'won' the anchor surprise. "
        "The Gaussian model predicts the same positive correlation in both halves.\n"
    )
    sign_groups = {
        "home beat the spread": (
            pairs.loc[pairs["anchor_resid"] > 0, "h_next_resid"],
            pairs.loc[pairs["anchor_resid"] > 0, "a_next_resid"],
        ),
        "away beat the spread": (
            pairs.loc[pairs["anchor_resid"] < 0, "h_next_resid"],
            pairs.loc[pairs["anchor_resid"] < 0, "a_next_resid"],
        ),
    }
    out.append(md_table(summary_rows(sign_groups)) + "\n")

    # 2b. Same-sign rate in the "both over or both under" framing
    out.append("### Same-sign rate (both overperform or both underperform)\n")
    be_same = 0.5 + be / 2
    out.append(
        f"Equivalent statement of the hypothesis: the two next games land on the same side of "
        f"their lines more than 50% of the time. Break-even at {cfg.leg_odds_american:+.0f} is "
        f"**{be_same:.1%}**. Also shown: mean |sum of residuals| (larger than the shuffled "
        f"baseline would mean the pair is jointly more dispersed).\n"
    )
    np_ = pairs[(pairs["h_next_resid"] != 0) & (pairs["a_next_resid"] != 0)]
    same = np.sign(np_["h_next_resid"]) == np.sign(np_["a_next_resid"])
    rng = np.random.default_rng(0)
    shuffled = np.mean([
        np.abs(np_["h_next_resid"].to_numpy() + rng.permutation(np_["a_next_resid"].to_numpy())).mean()
        for _ in range(200)
    ])
    ss_rows = []
    for lo, hi in [(0, 3), (3, 7), (7, 14), (14, 21), (21, 1000)]:
        m = (np_["abs_surprise"] >= lo) & (np_["abs_surprise"] < hi)
        ss_rows.append({
            "anchor |surprise|": f"[{lo}, {hi})", "n": int(m.sum()),
            "same_sign": round(float(same[m].mean()), 4), "se": round(float(np.sqrt(0.25 / m.sum())), 4),
            "mean_abs_sum": round(float((np_.loc[m, "h_next_resid"] + np_.loc[m, "a_next_resid"]).abs().mean()), 2),
        })
    ss_rows.append({"anchor |surprise|": "all", "n": len(np_), "same_sign": round(float(same.mean()), 4),
                    "se": round(float(np.sqrt(0.25 / len(np_))), 4),
                    "mean_abs_sum": round(float((np_["h_next_resid"] + np_["a_next_resid"]).abs().mean()), 2)})
    out.append(md_table(pd.DataFrame(ss_rows)) + "\n")
    out.append(f"Shuffled-pairs baseline for mean |sum|: {shuffled:.2f}.\n")

    # 3. Mechanical ROI
    out.append("## 3. Mechanical two-sided parlay ROI\n")
    out.append(
        "Each pair gets two 1-unit parlays: (cover, cover) and (fail, fail) for spreads; "
        "(over, under) and (under, over) for totals. Pushes refund. This isolates the "
        "correlation edge from any directional (marginal) edge.\n"
    )
    roi_rows = []
    for label, (x, y, sgn) in {
        "spread, all pairs": (pairs["h_next_resid"], pairs["a_next_resid"], 1),
        "spread, |surprise| >= 14": (
            pairs.loc[pairs["abs_surprise"] >= 14, "h_next_resid"],
            pairs.loc[pairs["abs_surprise"] >= 14, "a_next_resid"],
            1,
        ),
        "spread, new QB": (pairs.loc[pairs["new_qb_any"], "h_next_resid"], pairs.loc[pairs["new_qb_any"], "a_next_resid"], 1),
        "total, all pairs": (pairs["h_next_tresid"], pairs["a_next_tresid"], -1),
    }.items():
        r = two_sided_parlay_roi(x, y, d, expected_sign=sgn)
        roi_rows.append({"strategy": label, "pairs": r.n_pairs, "staked": r.staked, "profit": round(r.profit, 1), "roi": round(r.roi, 4), "hit_rate": round(r.hit_rate, 4)})
    out.append(md_table(pd.DataFrame(roi_rows)) + "\n")

    # 4. Kalman generalization
    out.append("## 4. Whole-network version (Kalman filter on market errors)\n")
    train = games[games["season"] <= TRAIN_SEASONS_END]
    test = games[games["season"] > TRAIN_SEASONS_END]
    kf = MarketErrorKalman(KalmanParams())
    fitted = kf.fit(train)
    lat, nxt = gaussian_explaining_away_corr(fitted.prior_std, fitted.obs_std)
    out.append(
        f"Hyperparameters fitted by predictive likelihood on {train['season'].min()}–{TRAIN_SEASONS_END}: "
        f"prior_std={fitted.prior_std:.2f}, process_std={fitted.process_std:.2f}, "
        f"obs_std={fitted.obs_std:.2f}, persistence={fitted.persistence:.3f}.\n\n"
        f"Implied single-shared-game correlations in the Gaussian model: latent errors "
        f"{lat:.4f}, next-game residuals about {nxt:.5f}. Break-even needs {be:.3f}.\n"
    )
    res = kf.run(test)
    kp = res.pairs
    slope, se, pv = kalman_slope(kp)
    out.append(
        f"Out-of-sample {TRAIN_SEASONS_END + 1}–{test['season'].max()}: {len(kp)} same-week game pairs. "
        f"Predicted |corr| ranges {kp['pred_corr'].abs().min():.4f}–{kp['pred_corr'].abs().max():.4f} "
        f"(mean |corr| {kp['pred_corr'].abs().mean():.4f}). Regressing realized residual product on "
        f"predicted covariance: slope={slope:.2f} (se {se:.2f}, p={pv:.3f}); 1.0 means the model's "
        f"covariances are right on average, 0 means no realized signal.\n"
    )
    cal = kalman_pair_calibration(kp, n_quantiles=10)
    cal["n"] = cal["n"].astype(int)
    cal["bin"] = cal["bin"].astype(int)
    out.append(md_table(cal) + "\n")
    top = kp[kp["pred_corr"] >= kp["pred_corr"].quantile(0.9)]
    bot = kp[kp["pred_corr"] <= kp["pred_corr"].quantile(0.1)]
    r_top = two_sided_parlay_roi(top["resid_1"], top["resid_2"], d, 1)
    r_bot = two_sided_parlay_roi(bot["resid_1"], bot["resid_2"], d, -1)
    out.append(
        f"Betting the top decile of predicted positive correlation (same-sign parlays): "
        f"{r_top.n_pairs} pairs, ROI {r_top.roi:+.4f}. Bottom decile (opposite-sign parlays): "
        f"{r_bot.n_pairs} pairs, ROI {r_bot.roi:+.4f}.\n"
    )
    # Marginal check: does the Kalman mean predict residuals (market inefficiency)?
    g = res.games
    mres = stats.linregress(g["pred_mean"], g["resid"])
    tg_all = to_team_games(games, cfg)
    mm = tg_all["next_resid"].notna()
    lag1 = float(np.corrcoef(tg_all.loc[mm, "resid"], tg_all.loc[mm, "next_resid"])[0, 1])
    out.append(
        f"Side check on marginals: slope of realized residual on Kalman predicted mean = "
        f"{mres.slope:.2f} (se {mres.stderr:.2f}; 1.0 = market under-reacts exactly as the filter "
        f"says, 0 = market already efficient). Model-free: within-team lag-1 autocorrelation of "
        f"closing-line residuals = {lag1:+.4f} (n={int(mm.sum())}).\n"
    )

    # 5. Power check
    out.append("## 5. Power check on synthetic data\n")
    out.append(
        "Same pipeline on residuals simulated from the filter's generative model on the real "
        "schedule, with an *efficient* market that re-prices every game at the Bayesian "
        "posterior given earlier games. This is the regime in which the explaining-away "
        "correlation exists at all: against a market that never updates, the latent error "
        "shows up as within-team persistence (a single-bet edge), not as cross-game correlation. "
        "`theory_next_corr` is the one-shared-game upper bound (week-1 anchors); later weeks are "
        "smaller because the market has already learned. If the effect existed at any of these "
        "sizes the backtest would see it.\n"
    )
    sched = games[["game_id", "season", "week", "gameday", "home_team", "away_team", "home_qb_id", "away_qb_id", "tresid"]]
    prow = []
    for label, params in {
        "fitted (real-world size)": fitted,
        "prior_std=6 (market off by 6 pts/team)": KalmanParams(6.0, 0.3, fitted.obs_std, 0.95),
        "prior_std=12 (market off by 12 pts/team)": KalmanParams(12.0, 0.3, fitted.obs_std, 0.95),
    }.items():
        sim = simulate_games(sched, params, seed=1, market="efficient")
        stg = to_team_games(sim, cfg)
        sp = build_shared_game_pairs(stg)
        s = correlation_summary(sp["h_next_resid"], sp["a_next_resid"], n_boot=300)
        rr = two_sided_parlay_roi(sp["h_next_resid"], sp["a_next_resid"], d, 1)
        _, theo = gaussian_explaining_away_corr(params.prior_std, params.obs_std)
        w1 = sp[sp["week"] == 1]
        s1 = correlation_summary(w1["h_next_resid"], w1["a_next_resid"], n_boot=100)
        prow.append({"scenario": label, "theory_next_corr": round(theo, 4), "pearson_week1": round(s1.pearson, 4), "pearson_all": round(s.pearson, 4), "ci_all": f"[{s.pearson_ci[0]:+.3f}, {s.pearson_ci[1]:+.3f}]", "phi_all": round(s.phi, 4), "two_sided_roi": round(rr.roi, 4)})
    out.append(md_table(pd.DataFrame(prow)) + "\n")

    # 6. Per-season
    out.append("## 6. Per-season spread correlation (shared-game pairs)\n")
    ps = pairs.groupby("season").apply(
        lambda q: pd.Series({"n": len(q), "pearson": np.corrcoef(q["h_next_resid"], q["a_next_resid"])[0, 1]}),
        include_groups=False,
    ).reset_index()
    ps["n"] = ps["n"].astype(int)
    ps["season"] = ps["season"].astype(int)
    out.append(md_table(ps) + "\n")
    frac_pos = float((ps["pearson"] > 0).mean())
    out.append(f"Seasons with positive correlation: {frac_pos:.0%} (coin flip = 50%).\n")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
