"""Backtest of shared (league-wide) latent factors for same-week NFL parlays.

Usage:
    python scripts/backtest_common_factor.py [--refresh] [--fast] [--out docs/experiments/parlay-common-factors.md]

Data location is controlled by ``GEO_MODEL_DATA_DIR`` (default ``data/raw``).
``--fast`` uses fewer permutations / bootstrap resamples (for smoke runs).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from geo_model.parlay import ParlayConfig, breakeven_correlation, load_games, parlay_ev
from geo_model.parlay import common_factor as cf

RESIDUALS: dict[str, str] = {"totals": "tresid", "spreads (home side)": "resid"}


def md_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub markdown table."""
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.astype(object).iterrows():
        lines.append("| " + " | ".join(_fmt(v) for v in r.tolist()) + " |")
    return "\n".join(lines)


def _fmt(v: object) -> str:
    if isinstance(v, (float, np.floating)):
        if np.isnan(v):
            return "nan"
        return f"{v:.4f}" if abs(v) < 10 else f"{v:.1f}"
    return str(v)


def _ci(ci: tuple[float, float], digits: int = 4) -> str:
    return f"[{ci[0]:+.{digits}f}, {ci[1]:+.{digits}f}]"


def pair_rows(groups: dict[str, tuple[pd.DataFrame, str, tuple[str, ...]]], d: float, n_boot: int) -> tuple[pd.DataFrame, dict[str, cf.PairStats]]:
    rows, objs = [], {}
    for label, (frame, col, group_cols) in groups.items():
        pairs = cf.same_slate_pairs(frame, col, group_cols)
        ps = cf.pair_stats(pairs, d, n_boot=n_boot)
        objs[label] = ps
        rows.append({"subset": label, **ps.to_row()})
    return pd.DataFrame(rows), objs


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--refresh", action="store_true", help="re-download the games and context files")
    ap.add_argument("--fast", action="store_true", help="fewer permutations/bootstraps")
    ap.add_argument("--out", default="docs/experiments/parlay-common-factors.md")
    args = ap.parse_args()

    cfg = ParlayConfig()
    ccfg = cf.CommonFactorConfig(n_permutations=200, n_boot=200) if args.fast else cf.CommonFactorConfig()
    games = load_games(cfg, refresh=args.refresh)
    try:
        ctx = cf.load_game_context(cfg, refresh=args.refresh)
    except Exception as exc:  # network unavailable and no sidecar cached
        print(f"context sidecar unavailable ({exc}); kickoff-window analysis skipped")
        ctx = None
    g = cf.add_context(games, ctx, ccfg)
    has_kick = "kickoff_window" in g.columns
    d = cfg.leg_decimal
    be = breakeven_correlation(d)
    be_same = 0.5 + be / 2
    t_end = ccfg.train_seasons_end
    oos = g[g["season"] > t_end]
    lo, hi = int(oos["season"].min()), int(oos["season"].max())
    n_comparisons = 0

    out: list[str] = []
    out.append("# Shared league-wide factors and same-week parlays: backtest\n")
    out.append(
        "Hypothesis: every game on a slate shares quantities the market estimates with error, "
        "e.g. the league scoring environment (rule changes, officiating points of emphasis, "
        "ball/weather season effects; hits totals) and the size of home-field advantage "
        "(hits spreads; e.g. the 2020 no-fans season). Unlike a team-level error, a shared-factor "
        "error is not diluted by opponent noise: it induces the same correlation across *every* "
        "game on the slate and accumulates across weeks. Books price same-week games in different "
        "matchups as independent, so a large enough shared-factor error relative to the closing line "
        "would make same-week parlays +EV (same-sign parlays if the factor is unknown, directional "
        "parlays if it can be tracked causally).\n"
    )
    out.append(
        f"Generated by `scripts/backtest_common_factor.py`. Data: nflverse games file, seasons "
        f"{cfg.seasons[0]}–{cfg.seasons[1]}, {cfg.game_types} games, {len(g)} games with closing spread and "
        f"total, {g.groupby(['season', 'week']).ngroups} (season, week) slates. Residuals are measured "
        f"relative to the closing line: `tresid = total - total_line` (positive = over), "
        f"`resid = result - spread_line` (positive = home covered). Kickoff times come from the nflverse "
        f"context sidecar (`gametime`, available from 2000; {'used' if has_kick else 'NOT available'}). "
        f"Kalman hyperparameters are fitted on {int(g['season'].min())}–{t_end} and every fitted-model "
        f"statistic is evaluated on {lo}–{hi}; all slate-level predictions use only earlier slates.\n"
    )

    # ------------------------------------------------------------------ 1
    out.append("## 1. What correlation is needed\n")
    out.append(
        f"At {cfg.leg_odds_american:+.0f} per leg (decimal {d:.3f}) a 2-leg parlay pays {d**2:.3f}. With 50/50 legs "
        f"the phi correlation between the two leg-win indicators must exceed **{be:.3f}** (same-sign rate "
        f"**{be_same:.1%}**) to break even. EV per unit at rho=0: {parlay_ev(0, d):+.3f}; rho=0.05: "
        f"{parlay_ev(0.05, d):+.3f}; rho=0.10: {parlay_ev(0.10, d):+.3f}. Under a shared-factor model with "
        f"factor variance `P` and single-game noise `obs_std²`, every same-slate pair has correlation "
        f"`P / (P + obs_std²)`; with obs_std about 13.4 points, break-even needs a factor std of about "
        f"{13.4 * np.sqrt(be / (1 - be)):.1f} points *unpriced by the closing line*.\n"
    )

    # ------------------------------------------------------------------ 2
    out.append("## 2. Week-level clustering (intraclass correlation)\n")
    out.append(
        "One-way random-effects ICC of the residual within a slate: under the random-effects model it is the "
        "correlation between two games on the same slate, i.e. exactly the parlay-relevant quantity. `pairwise` "
        "is the same quantity estimated as the Pearson correlation over all within-slate pairs (both orderings). "
        "`perm_*`: permutation test that shuffles residuals across slates *within the same season* (null keeps "
        "any season-level effect and tests slate-level clustering); `perm_p` is one-sided for positive "
        "clustering. `icc_ci` is a 95% slate-cluster bootstrap. The season-level row uses the whole sample "
        "as the permutation block. Slates with one game are dropped.\n"
    )
    groupings: dict[str, tuple[tuple[str, ...], str]] = {
        "(season, week), all seasons": (("season", "week"), "season"),
        f"(season, week), {lo}-{hi}": (("season", "week"), "season"),
        "(season, gameday)": (("season", "gameday_str"), "season"),
    }
    if has_kick:
        groupings["(season, gameday, kickoff window)"] = (("season", "gameday_str", "kickoff_window"), "season")
    groupings["(season): season-level factor"] = (("season",), "const")
    icc_all = []
    for res_label, col in RESIDUALS.items():
        for label, (group_cols, within) in groupings.items():
            frame = oos if label.endswith(f"{lo}-{hi}") else g
            frame = frame if within != "const" else frame.assign(const=0)
            r = cf.icc_with_tests(
                frame, col, group_cols, within_col=within, n_permutations=ccfg.n_permutations, n_boot=ccfg.n_boot, seed=ccfg.seed
            )
            icc_all.append({"residual": res_label, "slate": label, **r.to_row()})
    icc_tab = pd.DataFrame(icc_all)
    n_comparisons += len(icc_tab)
    out.append(md_table(icc_tab) + "\n")
    if has_kick:
        kw = g["kickoff_window"].value_counts(dropna=False)
        out.append(
            "Kickoff windows (Eastern): early = before 16:00, late = 16:00–19:59, night = 20:00+. Counts: "
            + ", ".join(f"{k}: {v}" for k, v in kw.items())
            + ".\n"
        )
    icc_week_tot = icc_tab[(icc_tab["residual"] == "totals") & (icc_tab["slate"] == "(season, week), all seasons")].iloc[0]
    icc_week_spr = icc_tab[(icc_tab["residual"] == "spreads (home side)") & (icc_tab["slate"] == "(season, week), all seasons")].iloc[0]
    icc_upper = max(float(str(icc_week_tot["icc_ci"]).split(",")[1].strip(" ]")), float(str(icc_week_spr["icc_ci"]).split(",")[1].strip(" ]")))
    sig_icc = icc_tab[icc_tab["perm_p"] < 0.05]
    out.append(
        f"Same-week ICC over all seasons: totals {icc_week_tot['icc']:+.4f} {icc_week_tot['icc_ci']}, spreads "
        f"{icc_week_spr['icc']:+.4f} {icc_week_spr['icc_ci']}. The break-even correlation is {be:.3f}, "
        f"{be / max(icc_upper, 1e-9):.0f}x the upper end of these intervals. "
        + (
            "No slate definition shows significant clustering (all one-sided permutation p >= 0.05)."
            if sig_icc.empty
            else "Rows with permutation p < 0.05: " + "; ".join(f"{r.residual} / {r.slate} (icc {r.icc:+.4f}, p {r.perm_p:.3f})" for r in sig_icc.itertuples())
        )
        + "\n"
    )

    # Strata ICC at the (season, week) level.
    out.append("### ICC by stratum, (season, week) slates\n")
    out.append(
        f"Pre-registered strata: early weeks 1-{ccfg.early_weeks} vs. later; 2020 (no fans) separately; and the first "
        "season after each of these league-wide environment changes:\n"
    )
    for rc in ccfg.rule_changes:
        out.append(f"- **{rc.season}** — {rc.label}: {rc.reason}")
    out.append("")
    masks = cf.stratum_masks(g, ccfg, evaluation_only=True)
    st_rows = []
    for res_label, col in RESIDUALS.items():
        for label, m in masks.items():
            r = cf.icc_with_tests(
                g[m], col, ("season", "week"), within_col="season", n_permutations=ccfg.n_permutations, n_boot=ccfg.n_boot, seed=ccfg.seed
            )
            st_rows.append({"residual": res_label, "stratum": label, **r.to_row()})
    st_tab = pd.DataFrame(st_rows)
    n_comparisons += len(st_tab)
    out.append(md_table(st_tab) + "\n")

    # ------------------------------------------------------------------ 3
    out.append("## 3. Persistence of the shared factor (strictly causal)\n")
    out.append(
        "Does the mean residual over the previous `k` weeks of the same season predict this week's residuals? "
        "OLS of each game's residual on the causal window mean, standard errors clustered by (season, week) "
        "because the predictor is constant within a week; `p` uses t with (weeks - 1) df. `game_sign_agree` is the "
        "fraction of games whose residual has the same sign as the predictor; `week_sign_agree` the fraction of "
        "weeks whose *mean* residual has the sign of the predictor (`week_sign_se` is the binomial SE at 50%). "
        "Windows `season` (all previous weeks this season) and `prev_season` (last season's full-season mean) "
        "test slow accumulation. Weeks without a full window are excluded. All seasons.\n"
    )
    windows: tuple[int | str, ...] = (*ccfg.persistence_windows, "season", "prev_season")
    persist: dict[str, pd.DataFrame] = {}
    for res_label, col in RESIDUALS.items():
        tab = cf.persistence_table(g, col, windows)
        persist[res_label] = tab
        n_comparisons += len(tab)
        out.append(f"### {res_label}\n")
        out.append(md_table(tab) + "\n")

    # ------------------------------------------------------------------ 4
    out.append("## 4. Scalar-state Kalman filter on the league offset\n")
    out.append(
        "The offset `theta` (league total offset for totals, league home-field offset for spreads) follows an AR(1) "
        "between consecutive slates (`persistence`, `process_std`) with a separate transition across season "
        "boundaries (`season_persistence`, `season_std`); every game observes `theta + N(0, obs_std²)`. The "
        "filter's prior variance `P` at a slate is the model's predicted covariance of any two residuals on that "
        "slate; `P / (P + obs_std²)` is the predicted same-week pair correlation. Hyperparameters are fitted by "
        f"predictive likelihood on {int(g['season'].min())}–{t_end} (Nelder-Mead, three starts) and evaluated on "
        f"{lo}–{hi}. `mean` is the market's long-run bias — a marginal, single-bet effect, not a correlation. "
        "The likelihood-ratio test compares the fit with the no-factor model (only `obs_std` and `mean` free; "
        "5 extra parameters).\n"
    )
    kal: dict[str, tuple[cf.ScalarFactorParams, cf.ScalarFactorOutput, cf.OlsResult, cf.OlsResult, float]] = {}
    for res_label, col in RESIDUALS.items():
        kf = cf.ScalarFactorKalman(value_col=col)
        fitted = kf.fit(g[g["season"] <= t_end])
        ll_train = kf.run(g[g["season"] <= t_end]).log_likelihood
        ll_null = cf.factor_profile(g[g["season"] <= t_end], col, (0.0,))["log_likelihood"].iloc[0]
        lr = 2 * (ll_train - ll_null)
        lr_p = float(stats.chi2.sf(max(lr, 0.0), df=5))
        res = kf.run(oos)
        cov_slope, mean_slope = cf.kalman_pair_calibration(res)
        kal[res_label] = (fitted, res, cov_slope, mean_slope, lr)
        sl = res.slates
        out.append(f"### {res_label}\n")
        out.append(
            f"Fitted: prior_std={fitted.prior_std:.3g}, process_std={fitted.process_std:.3g}, persistence={fitted.persistence:.3f}, "
            f"season_std={fitted.season_std:.3g}, season_persistence={fitted.season_persistence:.3f}, obs_std={fitted.obs_std:.2f}, "
            f"mean={fitted.mean:+.3f} (stationary within-season factor std "
            f"{fitted.stationary_std if np.isfinite(fitted.stationary_std) else float('inf'):.3g}). Training log-likelihood "
            f"{ll_train:.1f} vs. no-factor model {ll_null:.1f}: LR = {lr:.2f}, chi²(5) p = {lr_p:.3f}.\n"
        )
        out.append(
            f"Out-of-sample {lo}–{hi}: {len(sl)} slates, {len(res.games)} games. Predicted same-week pair correlation "
            f"ranges {sl['pred_pair_corr'].min():.5f}–{sl['pred_pair_corr'].max():.5f} (mean {sl['pred_pair_corr'].mean():.5f}; "
            f"break-even {be:.3f}). "
            + (
                "The fitted factor variance is numerically zero on every slate (the model found no shared factor), so "
                "the covariance calibration regression is not identified. "
                if res.factor_collapsed()
                else f"Regressing the realized same-week residual product on the predicted covariance (cluster-robust by slate): "
                f"slope = {cov_slope.slope:.2f} (se {cov_slope.se:.2f}, p = {cov_slope.p:.3f}; 1 = calibrated, 0 = no realized signal; "
                f"{cov_slope.n} pairs; "
                + ("a calibrated slope of 1 is rejected at 2 se" if abs(cov_slope.slope - 1.0) > 2 * cov_slope.se else "the interval covers both 0 and 1, i.e. uninformative")
                + "). "
            )
            + f"Regressing realized residuals on the filtered offset `pred_mean`: slope = {mean_slope.slope:.2f} "
            f"(se {mean_slope.se:.2f}, p = {mean_slope.p:.3f}; 1 = the market under-reacts exactly as the filter says, "
            f"0 = closing line already efficient).\n"
        )
        w1 = res.games[res.games["week"] == 1]
        w1_icc = cf.icc_oneway(w1["resid"].to_numpy(), cf.group_codes(w1, ("season", "week")))
        w1_pred = float(sl.loc[sl["week"] == 1, "pred_pair_corr"].mean())
        out.append(
            f"Season openers (week 1, {int((sl['week'] == 1).sum())} slates, {len(w1)} games): the filter's mean predicted pair "
            f"correlation is {w1_pred:.4f}; realized ICC {w1_icc.icc:+.4f} (pairwise {w1_icc.pairwise_corr:+.4f}, "
            f"{w1_icc.n_pairs} pairs, F-test p = {w1_icc.f_p:.2f}).\n"
        )
        unc = cf.icc_by_uncertainty(res, n_bins=4)
        out.append(
            "Realized within-slate ICC by quartile of the filter's predicted uncertainty (bin 3 = slates the model "
            "calls most uncertain, e.g. after a season boundary):\n"
        )
        out.append(md_table(unc) + "\n")
        n_comparisons += len(unc)

    out.append("### Profile likelihood: how large a shared factor do the data allow?\n")
    out.append(
        "For each stationary factor std `s` the offset is an AR(1) with that std (persistence 0.9 within season, 0.5 "
        "across seasons) and `obs_std`, `mean` are re-optimized. `delta_ll` is relative to `s = 0`; the 95% "
        "profile-likelihood bound is the largest `s` with `delta_ll >= -1.92` of the maximum. `pair_corr_stationary = "
        "s² / (s² + obs_std²)` is the same-week correlation a bettor faces without tracking the factor (what the ICC "
        "measures); `pair_corr_filtered` is the mean of the filter's `P / (P + obs_std²)`, what remains after learning "
        "from earlier slates. Reported separately on the training and the evaluation window.\n"
    )
    prof_rows = []
    profiles: dict[str, tuple[pd.DataFrame, pd.DataFrame]] = {}
    for res_label, col in RESIDUALS.items():
        p_train = cf.factor_profile(g[g["season"] <= t_end], col)
        p_test = cf.factor_profile(oos, col)
        profiles[res_label] = (p_train, p_test)
        for win, pr in ((f"{int(g['season'].min())}-{t_end}", p_train), (f"{lo}-{hi}", p_test)):
            ub = cf.profile_upper_bound(pr)
            obs = float(pr.loc[pr["factor_std"] == 0.0, "obs_std"].iloc[0])
            best = float(pr.loc[pr["log_likelihood"].idxmax(), "factor_std"])
            prof_rows.append(
                {
                    "residual": res_label,
                    "window": win,
                    "best_s": best,
                    "ub95_s": round(ub, 2),
                    "ub95_pair_corr": round(ub**2 / (ub**2 + obs**2), 4),
                    "delta_ll@s=1": round(float(pr.loc[pr["factor_std"] == 1.0, "delta_ll"].iloc[0]), 2),
                    "delta_ll@s=2": round(float(pr.loc[pr["factor_std"] == 2.0, "delta_ll"].iloc[0]), 2),
                    "delta_ll@s=4": round(float(pr.loc[pr["factor_std"] == 4.0, "delta_ll"].iloc[0]), 2),
                }
            )
    out.append(md_table(pd.DataFrame(prof_rows)) + "\n")
    for res_label, (p_train, p_test) in profiles.items():
        out.append(f"Full profile, {res_label}, {lo}–{hi}:\n")
        out.append(md_table(p_test[["factor_std", "obs_std", "mean", "delta_ll", "pair_corr_stationary", "pair_corr_filtered"]]) + "\n")

    # ------------------------------------------------------------------ 5
    out.append("## 5. Parlay implications\n")
    out.append("### Same-slate pairs: same-sign rate and two-sided parlay ROI\n")
    out.append(
        "All unordered pairs of games on the same slate. `pearson`/`phi` are the symmetric correlations of the two "
        "residuals / cover indicators; `same_sign` the fraction of no-push pairs landing on the same side (break-even "
        f"{be_same:.1%}). `two_sided_roi` bets both same-sign parlays on every pair (over/over and under/under, or "
        "cover/cover and fail/fail; pushes refund), isolating the correlation edge from any directional edge. All CIs "
        "are 95% slate-cluster bootstraps because same-slate pairs share games.\n"
    )
    pair_groups: dict[str, tuple[pd.DataFrame, str, tuple[str, ...]]] = {}
    for res_label, col in RESIDUALS.items():
        pair_groups[f"{res_label}: same week, {lo}-{hi}"] = (oos, col, ("season", "week"))
        pair_groups[f"{res_label}: same week, all seasons"] = (g, col, ("season", "week"))
        pair_groups[f"{res_label}: same gameday, {lo}-{hi}"] = (oos, col, ("season", "gameday_str"))
        if has_kick:
            pair_groups[f"{res_label}: same gameday + kickoff window, {lo}-{hi}"] = (oos, col, ("season", "gameday_str", "kickoff_window"))
    pair_tab, pair_objs = pair_rows(pair_groups, d, ccfg.n_boot)
    n_comparisons += len(pair_tab)
    out.append(md_table(pair_tab) + "\n")

    out.append("### Directional slate strategy\n")
    out.append(
        "Bet every game on the slate in the direction of a causal slate-level signal: the mean residual over the "
        "previous `k` weeks of the season (bet the slate's overs / home covers when it is positive, the unders / away "
        f"covers when negative; pre-registered primary window k = {ccfg.directional_window}), or the Kalman filter's "
        "filtered offset (computed before the slate, hyperparameters fitted on the training seasons). Singles at "
        f"{cfg.leg_odds_american:+.0f}; all 2-leg parlays among the slate's games in the same direction at "
        f"{d**2:.3f}. Pushes refund the single and any parlay containing it. ROI CIs are 95% slate bootstraps. "
        f"Evaluated on {lo}–{hi}.\n"
    )
    dir_rows = []
    best_dir: dict[str, cf.DirectionalResult] = {}
    for res_label, col in RESIDUALS.items():
        fitted, res, _, _, _ = kal[res_label]
        signals: dict[str, pd.Series] = {}
        for k in ccfg.persistence_windows:
            signals[f"prior {k}-week mean"] = cf.prior_window_mean(g, col, k)
        km = res.games.set_index("game_id")["pred_mean"]
        signals["Kalman offset incl. long-run bias"] = g["game_id"].map(km)
        signals["Kalman offset minus long-run bias"] = g["game_id"].map(km) - fitted.mean
        for s_label, sig in signals.items():
            gg = g.assign(_sig=sig.to_numpy())
            r = cf.directional_strategy(gg[gg["season"] > t_end], "_sig", col, d, n_boot=ccfg.n_boot, seed=ccfg.seed)
            dir_rows.append({"residual": res_label, "signal": s_label, **r.to_row()})
            if s_label == f"prior {ccfg.directional_window}-week mean":
                best_dir[res_label] = r
    dir_tab = pd.DataFrame(dir_rows)
    n_comparisons += len(dir_tab)
    out.append(md_table(dir_tab) + "\n")
    marg = oos[oos["tresid"] != 0]
    over_rate = float((marg["tresid"] > 0).mean())
    out.append(
        f"Marginal reference: over rate {lo}–{hi} = {over_rate:.4f} (n = {len(marg)}; a -110 single needs {1 / d:.4f}), "
        f"home cover rate = {float((oos.loc[oos['resid'] != 0, 'resid'] > 0).mean()):.4f}.\n"
    )

    # ------------------------------------------------------------------ 6
    out.append("## 6. Same-week pair correlation by stratum\n")
    out.append(
        f"Same-week pairs in each pre-registered stratum (rule-change seasons inside the training window are marked "
        f"in-sample and excluded from the best-case search). Break-even phi {be:.3f}, same-sign {be_same:.1%}.\n"
    )
    strat_rows = []
    phi_candidates: list[tuple[str, float, tuple[float, float], int]] = []
    for res_label, col in RESIDUALS.items():
        for label, m in masks.items():
            ps = cf.pair_stats(cf.same_slate_pairs(g[m], col, ("season", "week")), d, n_boot=ccfg.n_boot, seed=ccfg.seed)
            strat_rows.append({"residual": res_label, "stratum": label, **ps.to_row()})
            if "(in-sample)" not in label and np.isfinite(ps.phi):
                phi_candidates.append((f"{res_label}, {label}", ps.phi, ps.phi_ci, ps.n_no_push))
    strat_tab = pd.DataFrame(strat_rows)
    n_comparisons += len(strat_tab)
    out.append(md_table(strat_tab) + "\n")
    for label, ps in pair_objs.items():
        if f"{lo}-{hi}" in label and np.isfinite(ps.phi):
            phi_candidates.append((label, ps.phi, ps.phi_ci, ps.n_no_push))
    best = max(phi_candidates, key=lambda t: t[1])
    worst = min(phi_candidates, key=lambda t: t[1])

    # ------------------------------------------------------------------ 7
    out.append("## 7. Multiple comparisons and best case\n")
    out.append(
        f"Statistics examined in this report: {n_comparisons} table rows (ICC rows, persistence windows, Kalman "
        f"uncertainty bins, pair subsets, directional signals, strata), of which {len(phi_candidates)} are "
        f"out-of-sample same-week phi correlations in pre-registered subsets. With that many looks, one or two "
        f"nominal p < 0.05 results are expected under the null.\n"
    )
    out.append(
        f"Largest out-of-sample phi in any pre-registered subset: **{best[1]:+.4f}** {_ci(best[2])} ({best[0]}, "
        f"n = {best[3]} pairs). Most negative: {worst[1]:+.4f} {_ci(worst[2])} ({worst[0]}, n = {worst[3]}). "
        f"Break-even is {be:.3f} in either direction (opposite-sign parlays would exploit a negative correlation).\n"
    )
    excl = [c for c in phi_candidates if c[2][0] > 0 or c[2][1] < 0]
    big = max(phi_candidates, key=lambda t: abs(t[1]))
    out.append(
        f"{len(excl)} of the {len(phi_candidates)} out-of-sample phi intervals exclude zero"
        + (" (" + "; ".join(f"{c[0]}: {c[1]:+.4f}" for c in excl) + ")" if excl else "")
        + ". The subsets overlap (early weeks and kickoff windows are subsets of the full window) and single-season "
        f"intervals rest on 17-18 slates, so these are not independent looks. The largest |phi| is {abs(big[1]):.4f} "
        f"({big[0]}), {be / max(abs(big[1]), 1e-9):.1f}x below break-even.\n"
    )

    # ------------------------------------------------------------------ 8
    tot_all = pair_objs[f"totals: same week, {lo}-{hi}"]
    spr_all = pair_objs[f"spreads (home side): same week, {lo}-{hi}"]
    p_tot, p_spr = profiles["totals"][1], profiles["spreads (home side)"][1]
    ub_tot, ub_spr = cf.profile_upper_bound(p_tot), cf.profile_upper_bound(p_spr)
    obs_tot = float(p_tot.loc[0, "obs_std"])
    obs_spr = float(p_spr.loc[0, "obs_std"])
    icc_note = (
        "No slate definition (week, gameday, kickoff window, season) shows significant clustering."
        if sig_icc.empty
        else "Slate definitions with permutation p < 0.05: " + ", ".join(f"{r.residual} / {r.slate}" for r in sig_icc.itertuples()) + "."
    )
    out.append("## 8. Summary\n")
    out.append(
        f"- Same-week ICC (all seasons): totals {icc_week_tot['icc']:+.4f} {icc_week_tot['icc_ci']}, spreads "
        f"{icc_week_spr['icc']:+.4f} {icc_week_spr['icc_ci']}; permutation p = {icc_week_tot['perm_p']:.2f} / "
        f"{icc_week_spr['perm_p']:.2f}. {icc_note}\n"
        f"- Same-week pairs {lo}–{hi} ({tot_all.n_pairs} pairs in {tot_all.n_slates} slates, {tot_all.pairs_per_slate:.0f} per "
        f"week): totals phi {tot_all.phi:+.4f} {_ci(tot_all.phi_ci)}, same-sign {tot_all.same_sign:.1%}; spreads phi "
        f"{spr_all.phi:+.4f} {_ci(spr_all.phi_ci)}, same-sign {spr_all.same_sign:.1%}. Break-even is {be:.3f} / "
        f"{be_same:.1%}. Two-sided parlay ROI {tot_all.two_sided.roi:+.4f} (totals) and {spr_all.two_sided.roi:+.4f} (spreads), "
        f"i.e. the full vig.\n"
        f"- Causal persistence: no window (1, 2, 4, 8 weeks, season-to-date, previous season) predicts the current "
        f"week's residuals for totals; the largest |t| is {persist['totals']['t'].abs().max():.2f} (totals) and "
        f"{persist['spreads (home side)']['t'].abs().max():.2f} (spreads) over 12 windows.\n"
        f"- Kalman filter: the fitted league-offset model predicts same-week pair correlations of at most "
        f"{kal['totals'][1].slates['pred_pair_corr'].max():.4f} (totals) and {kal['spreads (home side)'][1].slates['pred_pair_corr'].max():.4f} "
        f"(spreads) out of sample. Calibration slopes of realized residual product on predicted covariance: "
        f"{kal['totals'][2].slope:.2f} (se {kal['totals'][2].se:.2f}) and {kal['spreads (home side)'][2].slope:.2f} "
        f"(se {kal['spreads (home side)'][2].se:.2f}) vs. 1 for a calibrated model. Likelihood-ratio tests vs. a no-factor "
        f"model: LR = {kal['totals'][4]:.2f} (totals), {kal['spreads (home side)'][4]:.2f} (spreads), 5 df.\n"
        f"- Profile likelihood ({lo}–{hi}): the stationary shared-factor std is at most {ub_tot:.2f} points for totals and "
        f"{ub_spr:.2f} for spreads (95%), i.e. same-week pair correlations of at most "
        f"{ub_tot**2 / (ub_tot**2 + obs_tot**2):.4f} and {ub_spr**2 / (ub_spr**2 + obs_spr**2):.4f} — about "
        f"{be / max(ub_tot**2 / (ub_tot**2 + obs_tot**2), 1e-9):.0f}x below break-even for totals.\n"
        f"- Directional strategy (bet the slate's side of the prior {ccfg.directional_window}-week mean): singles ROI "
        f"{best_dir['totals'].singles_roi:+.4f} {_ci(best_dir['totals'].singles_roi_ci, 3)} and parlays ROI "
        f"{best_dir['totals'].parlays_roi:+.4f} {_ci(best_dir['totals'].parlays_roi_ci, 3)} on totals; "
        f"{best_dir['spreads (home side)'].singles_roi:+.4f} and {best_dir['spreads (home side)'].parlays_roi:+.4f} on spreads.\n"
        f"- Best case: phi {best[1]:+.4f} {_ci(best[2])} ({best[0]}), against a hurdle of {be:.3f}.\n"
    )
    if best[1] < be and icc_upper < be:
        out.append(
            "**Conclusion:** relative to the closing line there is no measurable league-wide shared factor in NFL totals or "
            "spreads. Whatever scoring-environment or home-field drift exists is already in the closing number by the time "
            "a slate kicks off, and a filter that accumulates residual evidence across weeks has nothing left to learn. "
            "Same-week parlays in different matchups are priced correctly as independent.\n"
        )
    else:
        out.append(
            f"**Conclusion:** at least one pre-registered subset reaches the break-even correlation ({best[0]}: phi "
            f"{best[1]:+.4f}); check its confidence interval and the multiple-comparison count before acting on it.\n"
        )

    # ------------------------------------------------------------------ 9
    out.append("## 9. Caveats\n")
    out.append(
        "- Lines are a single closing consensus per game (nflverse); a bettor shopping across books, or betting early "
        "lines, faces a different (noisier) line and the ICC could differ relative to that line. Only the closing "
        "line is tested here.\n"
        f"- The ICC and pair statistics are model-free, so their all-season rows are not out-of-sample in the fitted "
        f"sense; the {lo}–{hi} rows and everything downstream of the Kalman fit are.\n"
        "- Rule-change seasons were chosen from public knowledge of league rule changes before looking at their "
        "residuals; they are single seasons (about 270 games, 17 slates), so their CIs are wide.\n"
        "- The Kalman model is Gaussian and scalar; a factor that only moves the tails, or that only affects a subset "
        "of games (dome vs. outdoor, primetime vs. early), would show up in the gameday/kickoff-window ICC rows only "
        "if it is large. Weather- and referee-conditioned factors are left to other tracks.\n"
        "- Multiple comparisons: see Section 7. The pre-registered primary statistics are the two same-week ICCs and "
        "the two same-week phi values; everything else is exploratory. The one nominal p < 0.05 persistence slope "
        "(if any) did not translate into a profitable directional strategy.\n"
    )
    out.append("## 10. Regenerate\n")
    out.append(
        "```shell\npython scripts/backtest_common_factor.py            # add --refresh to re-download, --fast for a smoke run\n"
        "python -m pytest tests/parlay/test_common_factor.py -q\n```\n"
    )

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
